hyperledger/indy-node

- sovrin_node/server/upgrade_log.py
This fixed the following tests which had previously failed on Windows 10:
- test_update_log,
- testNodeDetectsUpgradeDone,
- testSendNodeUpgradeToAllNodes,
- testNodeSchedulesUpgradeAfterRestart.
> Corrected the mode of opening a file for write via csv.writer.

- scripts/start_sovrin_node
Pass config to Logger in start_sovrin_node.py
This is required to allow manipulation logging behaviour by changing values in config.py or sovrin_config.py
> Pass config to Logger in start_sovrin_node

- scripts/load_test.py
Sometimes load test is needed on client-side, without sovrin-node installed
> Make load test be independent from other sovrin-node parts

- sovrin_node/test/suspension/helper.py
- sovrin_node/test/suspension/test_suspension.py
- had to re-implement some test helpers from sovrin-client (`changeVerkey` and `suspendRole`) because waiting `with pytest.raises` takes time rather nacks can be checked. `changeVerkey` and `suspendRole` are used only in sovrin-node and can be removed from sovrin-client later. Next `addRole` can be re-implement in 'check-nacks' approach but it is not in scope
- fix random fail of the testTrusteeCannotChangeVerkey test
> tests pass on the minimal configuration, SOV-1026

- sovrin_node/server/node.py
- sovrin_node/test/upgrade/test_pool_upgrade_reject.py
pool_upgrade wit force=True were allowed for everyone.
The fix added a validation to allow upgrade for trustee only
> Fix upgrage role validation in case of force=True

- sovrin_client/test/cli/test_nym.py
- sovrin_node/persistence/idr_cache.py
Without searching the existing batch duplicates can be written to the
ledger with different verkeys.
> fix for INDY-292 - search current batch for duplicate NYM txns

- getting-started.md
Fixing a broken link in the menu items in the Getting Started Guide.
> Fixed Broken Link in the Getting Started Guide

- getting-started.md
Updating Faber file name from "invitation" back to "request" per code
changes in INDY-457 and Kelly's request within the Getting Started
Guide.
> INDY-440 Updated Faber file name in documentation

- getting-started.md
Updated the Getting Started Guide to reflect the code change of "remote" where previously it was "target. Also fixed and clarified a sentence where DID was being defined.
> CS - 144 Getting Started Guide: Changed "Target" to "Remote"

- sovrin_client/agent/walleted.py
- sovrin_client/test/cli/test_merge_invitation.py
Positional arguments for the else case when proof
requests already existed case in
_merge_request were not correct and caused
the attributes member to not be created
correctly.
> Walleted.py merge_request Did Not Work

- sovrin_node/server/upgrader.py
- sovrin_node/test/upgrade/test_pool_upgrade_lower_version.py
- sovrin_node/test/upgrade/test_upgrader.py
Bug Fixed: POOL_UPGRADE only installs the latest build. You are not able to specify a version other than the latest to upgrade to.
Feature Added: POOL_UPGRADE should support downgrades
> Closes INDY-251, INDY-259

- sovrin_client/test/cli/test_node_demotion.py
- sovrin_client/test/cli/test_nym.py
- sovrin_common/auth.py
- sovrin_node/persistence/idr_cache.py
Adds second test to verify batches work when NYMs are different and batch fails when NYMs are the same
> fixes for batching "send NYM" requests (INDY-292)

- README.md
- getting-started.md
- setup.md
Note that there are also references to sovrin-foundation/sovrin-common which maybe should now be hyperledger/indy-common.
> fix pointers to old (bad) instructions

- getting-started.md
Updates verbiage in Getting Started Guide to reflect small changes due
to removing branding from Sovrin to Indy. I also updated verbiage
throughout to reflect actors specifically, where it made sense to do
so for the sake of clarity. Example, instead of just saying "Indy", I
changed it to "Indy code base" or "the ledger" or "the network."
Signed-off-by: TechWritingWhiz <TechWritingWhiz@gmail.com>
> Indy 894 Update verbiage in Getting Started Guide

- README.md
- cluster-simulation.md
- setup.md
Updates the the path of the Getting Started Guide to the stable branch rather than the master branch on the README.md file and  updates cluster-simulation.md and setup.md with the correct path to the Getting Started Guide.
> README_update Updates pathing to Getting Started Guide

- README.md
Adds a link to the Hyperledger Wiki-Indy page within the README.md file
in an effort to consolidate and encourage the wiki page to be the
main "hub" starting point for the Indy documentation.
Signed-off-by: TechWritingWhiz <TechWritingWhiz@gmail.com>
> README_update2 Adds a link to the Hyperledger Wiki-Indy page

- docs/Indy_Running_Locally.md
Updates the links to the Getting Started Guide and the Setup Instruction
to point to the stable version of each, rather than Master in indy-node/
docs/Indy_Running_Locally.md
Signed-off-by: TechWritingWhiz <techwritingwhiz@gmail.com>
> Update links to stable branch docs in Indy_Running_Locally

- indy_node/server/upgrader.py
- indy_node/test/upgrade/helper.py
- indy_node/test/upgrade/test_node_upgrade.py
- indy_node/test/upgrade/test_node_upgrade_unsuccessful.py
- If we send POOL_UPGRADE with force=true, then there is a chance that NODE_UPGRADE with IN_PROGRESS action will not be written to the ledger since all nodes in the pool are restarted at the same time, and the txn is getting lost and we have no consensus.
- After Node is restarted, it checked whether we had 1) START action in Upgrade log and 2)  NODE_UPGRADE with IN_PROGRESS action. If so, it sent Upgrade SUCCEESS or FAIL (depending on whether the current version equals to the expected one).
- In the situation with forced POOL_UPGRADE we didn't have IN_PROGRESS txn, so SUCCESS/FAIL NODE_UPGRADE txns may be not sent and written to the ledger
- It look like it's sufficient to check START action in Upgrade log only. If we have it, we send NODE_UPGRADE.
> INDY-799: Fix sending NODE_UPGRADE txn after Node is upgraded

- build-scripts/ubuntu-1604/postinst_node
- reverts commit 68335ea934542847f0a5edd1e5d03d4b2ee09246 because nofile limits were incorrectly added to node control service
- adds nofile limits for node service instead
> nofile limits for node service, reverted for node control

- docs/requests.md
- docs/transactions.md
- indy_client/cli/constants.py
- indy_client/test/cli/test_command_reg_ex.py
- indy_client/test/cli/test_nym_suspension.py
- indy_client/test/cli/test_send_nym_validation.py
- indy_common/identity.py
- indy_node/test/suspension/test_suspension.py
- setup.py
Now any NYM owner can flush its verkey. In this case permissions for verkey updating goes back to creator.
> INDY-582: support setting of empty (None) verkey on client and server sides

- indy_node/utils/node_control_tool.py
This condition allow to use node_control_tool.py with an agnostic approach towards Linux distros
> Removing apt-mark usage on non Debian distros

- indy_client/test/anon_creds/conftest.py
- indy_client/test/anon_creds/test_claim_def.py
- indy_client/test/anon_creds/test_schema.py
- indy_client/test/cli/test_send_claim_def.py
- indy_client/test/conftest.py
- indy_common/auth.py
- indy_common/test/auth/test_auth_claim_def.py
- indy_common/test/auth/test_auth_schema.py
- indy_node/server/domain_req_handler.py
- added validation for schema and claimDef adding
- expanded the permission map in auth.py
- added unit tests for auth.py
- added integration tests for domain_req_handler.py
> INDY-1111: prevent creating a schema or claimDef without role

- README.md
- docs/indy-running-locally.md
- getting-started.md
Changes:
- Removed all references to indy-running-locally from main documentation (README)
- Haved a bold warning in this script that it should not be used and Docker/Vagrant are appropriate options.
- Mentioned Docker-based solution from libindy repo to start the pool locally in README.
> INDY-1227: change documentation for indy-running-locally

- build-scripts/ubuntu-1604/postinst_node
see "Basic environment variable substitution is supported" part in
https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines
> fixes ExecStart systemd's option for node control tool

- README.md
- getting-started.md
Changes:
- remove link to Indy Cluster Simulation from readme
- remove link to Indy Cluster Simulation from GSG
> INDY-1227: remove link to Indy Cluster Simulation

- scripts/read_ledger
- setup.py
Since read-only mode is supported for RocksDB a copy of
ledger is not created in case of RocksDB-based ledger.
Also added additional checks to avoid removing of the
ledger instead of it's copy.
> INDY-1289: support read-only state in read_ledger with RocksDB.

- build-scripts/ubuntu-1604/postinst_node
* removes square brackets for optional argument from ExecStart
see "Basic environment variable substitution is supported" part in
https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines
* removes unnecessary quotes in ExecStart
> Hotfix in stable for node control tool

- getting-started.md
In the latest [Getting Started with Indy][target-master] document ([here][target-pinned] for the version-pinned link), it states that `DID` is the short form for `Distributed Identity`.
However, according to various sources below, I believe that the correct term should be `Decentralized Identity`:
- [W3C: Decentralized Identifiers (DIDs) v0.9][w3c]
- [Sovirn: Sovrin Glossary][glossary]
- [Sovirn: Sovrin Provisional Trust Framework][sptf]
[target-master]: https://github.com/hyperledger/indy-node/blob/master/getting-started.md#evaluate-a-connection-request
[target-pinned]: https://github.com/hyperledger/indy-node/blob/c5db000fe39ae4000b543d2d77e32be2ff0c156f/getting-started.md#evaluate-a-connection-request
[w3c]: https://w3c-ccg.github.io/did-spec/
[glossary]: …
> Fixed typo for DID: from 'Distributed Identifier' to 'Decentralized Identifier'

- README.md
- environment/README.md
- environment/vagrant/README.md
- getting-started.md
To install and run a test network of nodes on one's computer for development purposes, there are several methods available to use. However, lately only Docker has been supported. Vagrant is more difficult to use, and in many cases breaks completely. Several new, interested developers have been caught trying to use Vagrant and failing because they should be following the more-updated Docker instructions instead.
To fix this problem, Vagrant needs to be marked as deprecated in various places in indy-node's Github repository.
Signed-off-by: ryanwest6 <31378238+ryanwest6@users.noreply.github.com>
> Deprecated Vagrant method for running test network

- indy_node/server/action_req_handler.py
- indy_node/server/config_req_handler.py
- indy_node/server/node.py
- indy_node/server/restarter.py
- indy_node/server/upgrader.py
- indy_node/test/helper.py
- indy_node/test/upgrade/test_forced_upgrade_if_ordered_and_then_request_received.py
- indy_node/test/upgrade/test_forced_upgrade_if_request_received_after_propagate.py
- indy_node/test/upgrade/test_node_handles_forced_upgrade_on_client_request.py
- indy_node/test/upgrade/test_node_handles_forced_upgrade_on_propagate.py
- setup.py
- Added tests verifying different cases of handling of `POOL_UPGRADE force=true` request.
- Provided `Node.is_txn_writable` method implementation for indy-node.
- Renamed `handleActionTxn` methods in `Upgrader` and `Restarter` classes using different names since they do not use common interface.
> INDY-1447: Fixed handling of forced requests

- indy_node/server/restarter.py
- indy_node/test/pool_restart/test_pool_restart.py
After scheduled restart in initializing Restarter the method ```_update_action_log_for_started_action``` is called. It has a bug and test test_restarter_can_initialize_after_pool_restart schould detect it.
> INDY-1741: Bugfix problem with Restarter after scheduled restart 

- pool_automation/roles/aws_manage/defaults/main.yml
- pool_automation/roles/aws_manage/tasks/main.yml
The PR fixes an infinite loop in aws_manage defaults when no inventory is defined: 
`aws_inventory_dir` <-> `aws_tag_namespace`
> [INDY-1827] Fixes aws_manage role variables relationship

- pool_automation/roles/aws_manage/tasks/set_known_hosts.yml
- ssh-keyscan fails silently, thus need to check its output and retry if nothing has been returned
> [Pool Automation][INDY-1899] Fixes host keys scan routine

- environment/docker/pool/README.md
The --with-default-names option is removed, so it is not available anymore.
https://github.com/Homebrew/homebrew-core/commit/068955e8cd698ac0286302fd244a4e4b42b47bab
> Fix the deprecated option of gnu-sed

- README.md
`Getting Started Guide` is move to `Indy Workthrough`.
> Getting Started Guide is moved.

- docs/source/requests-new.md
- docs/source/requests.md
- docs/source/transactions.md
The description of the content of a transaction, and in particular a node transaction, is not consistent with the current workings of indy-node. While in the [transactions README](https://github.com/hyperledger/indy-node/blob/master/docs/source/transactions.md) is stated that the `dest` field of a node transaction is a node DID, it is instead the node verification key (as also shown by the test scripts, where the verification key of the node is written in the pool transaction, and not it public key).
> Update transaction structure description.

- indy_node/server/domain_req_handler.py
- indy_node/test/claim_def/test_send_claim_def.py
- a Schema's seqNo a Claim def is pointing to may be in uncommitted state, especially if this is processing of stashed requests after catchup
> fix claim def validation

- build-scripts/ubuntu-1604/Dockerfile
- updates setuptools in docker env since old version from `ubuntu:xenial` leads to intermittent failures durinf `fpm` tool run
> [INDY-2105] Fixes debs build routin in CD pipeline

- design/txn_author_agreement.md
- docs/source/auth_rules.md
- docs/source/requests.md
- docs/source/transactions.md
- indy_common/authorize/auth_constraints.py
- indy_common/authorize/authorizer.py
- indy_common/test/auth/metadata/test_error_messages.py
- Fix/extend docs for AUTH_RULE and GET_AUTH_RULE
- Add docs about TAA and TAA_AML transactions and requests
- Add docs about Revocation transactions and requests
- Extend Auth Rules with TAA and TAA_AML
- Extend Auth Rules with a description on who is the owner for each action
- Remove anyone_can_write docs from Auth Rules
- Add more tests for error messages when metadata is set
> INDY-2074: Extend documentation for Auth Rules, TAA and Revocation

- scripts/restart_indy_node_ubuntu1604.sh
After the indy_node_control process downloads a new version of software, it invokes /usr/local/bin/restart_indy_node which then invoked `supervisorctl restart indy-node-control`.  Unfortunately this command is not atomic and is equivalent to `supervisorctl stop indy-node-control` followed by `supervisorctl start indy-node-control`, which results in NOT restarting indy-node-control because it has just stopped itself.
The fix is for indy-node-control to simply commit suicide so that supervisord will automatically restart the process; that is, from a supervisorctl perspective, we do not change the state of the indy-node-control service.
Signed-off-by: Keith Smith <bksmith@us.ibm.com>
> Fix restart_indy_node under supervisord

- indy_node/test/anon_creds/test_revoc_def_static_validation.py
Signed-off-by: Brent Zundel <Brent.Zundel@gmail.com>
The random integer function currently allows a 0 to be returned if the `request.param` is `lt`, but if the returned 0 is then used by `revoc_def_req` as a parameter for `randomString` this will result in an error. Because the range is usually 0-255, this error is intermittent.
This PR adjusts the range of possible returned random values so that 1 is the lowest possible return value.
> fix returned random size

- indy_node/server/request_handlers/domain_req_handlers/nym_handler.py
- indy_node/test/nym_txn/test_nym_auth_rules.py
- indy_node/test/nym_txn/test_nym_no_role.py
- indy_node/test/request_handlers/test_nym_handler.py
modifies nym transaction dynamic validation to check for `role` and `verkey` properties in the operation, fails if both are missing.
> nym dynamic validation check transaction w/out verkey or role

- .github/workflows/build.yaml
This will let people trigger builds without a change.
Signed-off-by: Ry Jones <ry@linux.com>
> chore: Add workflow trigger

- scripts/remove_ledger.py
> Add script for remove ledger

- .github/workflows/build.yaml
- The actions don't have access to publish test results to commits on a PR.
- This should not cause the job to fail.
Replicating the fix done for `indy-plenum`; https://github.com/hyperledger/indy-plenum/pull/1523
Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>
> Allow test report publishing to fail

- .gitattributes
- .github/actions/publish-deb/action.yaml
- .github/actions/publish-deb/publishPackages
- .github/actions/publish-deb/upload-spec.json
- .github/actions/set-version/action.yaml
- .github/workflows/README.md
- .github/workflows/build.yaml
- .github/workflows/build/Dockerfile
- .github/workflows/lint/Dockerfile
- Jenkinsfile.ci
- build-scripts/ubuntu-1604/build-3rd-parties.sh
- ci/ubuntu.dockerfile
- indy_node/__metadata__.py
- runner.py
- Following the pattern and enhancements developed for the plenum workflows; https://github.com/hyperledger/indy-plenum/pull/1541
- Update test runner (`runner.py`) to automatically report the test results for each set of tests.
- Enhancements from https://github.com/hyperledger/indy-plenum/commit/06d9406e611784b7005829ca325fcaa3ae435ea5
> Add support for publishing Debian packages

- .github/actions/publish-deb/publishPackages
- .github/actions/publish-deb/upload-spec.json
This PR rearranges the uploading structure of the debian files according to the changes made in Indy-Plenum in this [commit](https://github.com/hyperledger/indy-plenum/commit/52ddd72c0dec5f037396bf0e88acbd38d13cdb4d).
The new structure prevents errors in uploading of debian files with the same filename but build from a different distribution.
The new structure will be as follows:
- `indy/pool/xenial/[dev, main, rc, stable]`
- `indy/pool/bionic/[dev, main, rc, stable]`
- `indy/pool/focal/[dev, main, rc, stable]`
> fix uploading of deb files with the same name but different distribution

- setup.py
Update version of Indy SDK to the same version used in Indy-Plenum which is at `python3-indy==1.15.0-dev-1625`
> Update version of Indy SKD

- .github/workflows/build.yaml
- For example, support publishing off the `ubuntu-20.04-upgrade` branch.
> Support publishing off a development branch

- .github/workflows/build.yaml
The recently merged CI/CD pipeline in #1697 missed passing `distribution` as env variable in the `publish-artifacts` step. This PR fixes the issue so that the debian packages get uploaded to the correct directory.
> Ubuntu 20.04: bug fix: added missing env of distribution in publish_artifacts

- .github/workflows/build/Dockerfile
- Jenkinsfile.ci
- build-scripts/ubuntu-1604/Dockerfile
- ci/code-validation.dockerfile
- ci/pipeline.groovy
- ci/ubuntu.dockerfile
- setup.py
This PR updates the version of the PyPI package of indy-plenum from 1.13.0.dev1034 (build and published by Jenkins instance of Sovrin) to version 1.13.0.dev143. This version was published in the latest successful GHA run from the master branch. The GHA run is at: https://github.com/hyperledger/indy-plenum/runs/3579890752?check_suite_focus=true
This change is the precondition to start migrating from https://repo.sovrin.org/deb/pool/xenial/ to https://hyperledger.jfrog.io/ui/native/indy/pool/xenial.
Also, this update is required to run the node system tests from https://github.com/hyperledger/indy-test-automation/ with the Debian files built and published in the new CI/CD pipeline.
Further, this PR contains some fixes for the Jenkins CI pipeline.
A successful run can be found at: …
> changed plenum version to 1.13.0.dev143 from GHA and fixed ci

- build-scripts/ubuntu-1604/prepare-package.sh
This needs to be re-added so the packages get named accordingly to the naming convention with the `python3` prefix.
> re-added the adjustment of packages for the cannonical archive

- .github/workflows/build.yaml
This PR updates the GitHub Action [setup-jfrog-cli](https://github.com/jfrog/setup-jfrog-cli) from `v1` to `v2`. The default version of the `jfrog-cli` changes from `v1.51.1` to `v2.3.0`.
Currently, the publishing of 3rd-party-dependencies doesn't work and this update is an attempt to [fix the current issue](https://github.com/hyperledger/indy-node/runs/4097177887?check_suite_focus=true#step:9:36).
> updated version of setup-jfrog-cli to v2

- build-scripts/ubuntu-1604/prepare-package.sh
This change is needed to replace the PyPI version of `plenum` with the version of the Debian artifact.
Otherwise, we run into this error:
`indy-node : Depends: indy-plenum (= 1.13.0.dev169) but 1.13.0~dev169 is to be installed`
> prepares indy-plenum package version of debian version depedency

- .github/workflows/build/Dockerfile.ubuntu-2004
- build-scripts/ubuntu-2004/build-3rd-parties.sh
- setup.py
This PR bumps the version of `Indy Plenum`  to `1.13.0.dev175`.
Also, this PR adds the most recent version names to the 3rd party artifacts.
> bump version of indy plenum and added pypi versio to 3rd party artifacts

- build-scripts/ubuntu-2004/prepare-package.sh
This PR fixes the following error when installing indy-node from the Artifactory:
```bash
#10 3.567 The following packages have unmet dependencies:
#10 3.617  indy-node : Depends: indy-plenum (= 1.13.0.dev175) but 1.13.0~dev175 is to be installed
#10 3.617              Depends: timeout-decorator (>= 0.5.0) but it is not installable
#10 3.617              Depends: distro (>= 1.5.0) but it is not installable
```
> set dependencies for the Cannocical archive

- .github/workflows/build.yaml
Signed-off-by: pSchlarb <p.schlarb@esatus.com>
> Fixes wrong max slices in GHA

- .github/workflows/build.yaml
- .github/workflows/indy_test_automation.yml
This PR contains the workflow to run the `indy-node-tests` from https://github.com/hyperledger/indy-test-automation.
Currently, the workflow is only triggered if the `GITHUB_REF` is `rc`.
The trigger of the `indy-test-automation` workflow needs some more automation in terms of setting the input parameters dynamically.
The `WORKFLOW_DISPATCH_TOKEN` that is used to trigger the workflow is not accessible to PRs. (https://chat.hyperledger.org/channel/indy-contributors?msg=Gxj3huBNEMyCNiNwP)
A successful run of the `indy-test-automation` workflow is at https://github.com/udosson/indy-node/actions/runs/1687056439
The workflow currently only works for Indy based on Ubuntu 16.04 because a suitable `systemd` image for the Ubuntu 20.04 Node container is still missing.
> Indy-Test-Autmation

- .gitpod.Dockerfile
- .gitpod.yml
- README.md
Addition of Gitpod specific files.
> Gitpod DevContainer

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .vscode/settings.json
- pytest.ini
Addition of VSCode Devcontainer files.
> VSCode Devcontainer

- pytest.ini
- Set asyncio_mode = auto to support the new operating modes of pytest-asyncio>=0.17
- https://github.com/pytest-dev/pytest-asyncio#modes
> Fix pytest-asyncio deprecation warnings which are causing the tests to fail.

- docs/source/setup-dev.md
> DevContainer documentation

- indy_common/config.py
- python3-pygments and python3-intervaltree do not exist as dependencies in plenum anymore.
- The `indy-node-control` crashes when trying to hold packages that don't exist.
- Fixes the issue found here; https://github.com/hyperledger/indy-test-automation/issues/113
> Fix crash in `indy-node-control`

- .github/workflows/build/Dockerfile.ubuntu-1604
- Jenkinsfile.ci
- ci/pipeline.groovy
- indy_node/__init__.py
- setup.py
Removal of Pip Imports for ubuntu20
and 
version bump for indy-sdk (getting rid of pip complaining about wrong indy-sdk versions, which was fixed)
Signed-off-by: pSchlarb <p.schlarb@esatus.com>
> Remove Pip Imports for ubuntu20

- indy_node/test/conftest.py
- Add filter for zmq unclosed socket warnings from updated zmq version.
> Add warning filter

- build-scripts/ubuntu-2004/prepare-package.sh
- setup.py
This should fix the wrong dependency in the indy-node .deb package.
> The following packages have unmet dependencies:
>  indy-node : Depends: importlib-metadata (< 3.0) but it is not installable
Signed-off-by: mgmgwi <guido.wischrop@mgm-tp.com>
> fix importlib-metadata dependency

- .github/workflows/PR.yaml
- .github/workflows/releasepr.yaml
Added `StatusCheck` job  (Always true, when executed) for the branch protection rules(blocks merging while test are running and if tests fail).
Job needs to be ran at least once to be able to select it in the branch protection rule settings.
Signed-off-by: pSchlarb <p.schlarb@esatus.com>
> Added Status Check for branch protection

- .github/workflows/PR.yaml
- .github/workflows/releasepr.yaml
- Fix error in releasepr.yaml
- Ensure the triggers on PR.yaml and releasepr.yaml are mutually exclusive.
> Adjust workflow triggers.

- .github/workflows/tag.yaml
- build-scripts/ubuntu-2004/build-3rd-parties.sh
- build-scripts/ubuntu-2004/build-indy_node.sh
- build-scripts/ubuntu-2004/prepare-package.sh
- setup.py
- A fix for the dependency scheme related to indy-plenum.  Fixes the issue where the python package version installed using the deb package is different than the published python package.
- The issue was due to how the dependency options of `fpm` were being used.  The deb package build was using the python dependencies to define the deb package dependencies.  Since the deb and python package version numbers use slightly different formats for non-release (`dev` and `rc`) versions, the versions of the python dependencies (notably indy-plenum) were being set to match the deb version format in order to correctly define the deb dependencies.  This strategy has the unfortunate side affect of causing dependency issues with the python packages down the road.
Signed-off-by: Wade Barnes …
> Fix dependency scheme

- docs/source/requests.md
fixed broken links related to `auth_rules.md` in the page [Requests](https://hyperledger-indy.readthedocs.io/projects/node/en/latest/requests.html)
issue #1683
> fixed broken links

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
This is a workaround to fix the indy-node devcontainer issues reported in https://github.com/hyperledger/indy-node/issues/1822.  The dependency issues are actually at the indy-plenum level.  I'll be opening a ticket for the issue there.
fixes: https://github.com/hyperledger/indy-node/issues/1822
> Fix indy-node devcontainer build issues

- .github/workflows/build/Dockerfile.ubuntu-2004
- setup.py
This PR updates the indy-plenum version in `setup.py` to use `indy-plenum==1.13.1`.
> Update to indy-plenum==1.13.1

- .github/actions/getNewNodeVersion/action.yaml
- .github/workflows/PR.yaml
- .github/workflows/Push.yaml
- .github/workflows/publishRelease.yaml
- .github/workflows/releasepr.yaml
- .github/workflows/repoDispatchable_UpdatePlenumDependency.yaml
- .github/workflows/reuseable_test.yaml
- .github/workflows/tag.yaml
- Address warning raised while running workflows.
> Upgrade GHA versions

- design/anoncreds.md
- design/pool_restart_txn.md
- design/transaction_endorser.md
- design/txn_author_agreement.md
- design/validator_info.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "Enteries" to "Entries".
Corrected "tailsLocaiton" to "tailsLocation".
Corrected "Flase" to "False".
Corrected "reqeust" to "request".
Corrected "ommited" to "omitted".
Corrected "identidier" to "identifier".
Corrected "uptaime" to "uptime".
Please review the changes and let me know if any additional changes are needed.
> fix: typos in documentation files

- .github/workflows/scorecard.yml
- README.md
Addresses #1897  by adding the badge and the scorecard task that will execute weekly.  Once this is merged, I'll run it manually. Until it has been run at least once. the badge won't generate and the link won't resolve. But that's OK -- we'll get it run.
> Adds OpenSSF scorecard workflow and badge
