sovrin_node/__metadata__.py

Fixing version to work with automatic deploy

Hotfix: Version

---

sovrin_node/server/node.py
sovrin_node/server/upgrader.py
sovrin_node/test/helper.py
sovrin_node/test/upgrade/test_communication_with_control_service.py

Adds node name to upgrade notifications. It is helpful when you are subscribed to notifications from multiple nodes.

Node name to upgrade notification messages

---

scripts/upgrade_sovrin_node_ubuntu1604.sh
scripts/upgrade_sovrin_node_ubuntu1604_test.sh

Additional minor fix to refresh systemd service units

Reload systemd services after upgrade on ubuntu

---

sovrin_node/server/node.py
sovrin_node/server/upgrader.py
sovrin_node/test/upgrade/test_communication_with_control_service.py
sovrin_node/test/upgrade/test_upgrade_timeout.py

Support of timeout after which started upgrade will be declared as failed

Upgrade timeout

---

sovrin_node/server/node.py

Replaces transaction CLAIM_DEF to SCHEMA and updates related code

Replace CLAIM_DEF by SCHEMA

---

sovrin_node/test/upgrade/test_pool_upgrade.py

Skipped failing tests, when ran with whole module

---

sovrin_node/test/upgrade/test_pool_upgrade.py
sovrin_node/test/upgrade/test_pool_upgrade_through_catchup.py

Skipping failing test of pool upgrade for windows

Skip upgrade test on windows

---

scripts/clear_node.py

* add basic scripts for removing data
* implement advance script for clearing data
* rename cleanup to clear_node

Clean data script (#42)

---

docs/Sovrin_Running_Locally.md

pytest is required for passing though getting started tutorial - agents cannot be started without it

Add pytest installation note to sovrin_running_locally guide

---

scripts/upgrade_sovrin_node.bat
scripts/upgrade_sovrin_node_test.bat
scripts/upgrade_sovrin_node_ubuntu1604.sh
scripts/upgrade_sovrin_node_ubuntu1604_test.sh

Now pip and deb installation does not replace existing transaction by default template

Do not backup transaction files on upgrade

---

sovrin_node/server/node.py

relies on invalid-port-range-fix PR in plenum

switch to new check_endpoint_valid function

---

sovrin_node/server/node.py

There are some important changes in master that are needed in this branch

Merge master

---

scripts/start_sovrin_node
sovrin_node/server/node.py
sovrin_node/server/upgrader.py
sovrin_node/test/helper.py

Updated imports of logging since it was moved stp repo

Fix imports for logging-related things

---

scripts/load_test.py

There were some changes done in project after which load script need to be updated

Fix load test

---

setup.py

Up common version to 0.2.29

---

setup.py
sovrin_node/server/node.py
sovrin_node/test/replay/test_ledger_replay.py

Make fixes related to renaming issuer key and moving type field to it from SCHEMA
*Tests can fail, because there is no required build of some dependencies yet*
*Sending request for review only*

Rename ISSUER_KEY to CLAIM_DEF

---

sovrin_node/server/domain_req_handler.py
sovrin_node/server/node.py

This pr brings fix that moves signature type from key to value

Fixes for processing claim def in domain request handler

---

setup.py

Up commons version to 0.2.43, clients to 0.3.61

Up commons version to 0.2.43, clients to 0.3.61

---

setup.py

- Up commons to 0.2.45
- Up client to 0.3.63

Up commons and client version

---

setup.py

Client - 0.3.67
Commons - 0.2.48

Up versions of dependencies

---

scripts/load_test.py

Adds support of sending GET_NYM requests

Add support of GET_NYM for load test

---

sovrin_node/pool/local_pool.py

small tweak for local_pool.py
for module changes in client
few other tweaks to make things more clear.

Agent generalization

---

setup.py

- Updated sovrin-common-dev dependency.
- Updated sovrin-client-dev dependency.

Updated dependencies

---

scripts/load_test.py

totalTimeout can be huge for load tests but 'eventually' has
an assertion which limits the timeout

remove a dependency from "eventuallyAll" in load_test.py

---

scripts/load_test.py

Remove query time counter since it is not measured

---

setup.py
sovrin_node/server/node.py

- Up versions of commons and client
- Use defaultFile when creating Ledger

Fix usage of ChunkedFileStore

---

sovrin_node/server/node.py

This allows default file to be located no only in base location specified in config

Replace self.config.baseDir by self.basedirpath in node to make base dir be configurable for each node

---

data/migrations/0_3_123_test.py

Reverts sovrin-foundation/sovrin-node#164

Revert "Test migrations"

---

setup.py

Up versions

---

setup.py
sovrin_node/test/attrib_txn/test_n_minus_f_pool_processes_attrib.py
sovrin_node/test/helper.py

* bump sovrin-common-dev==0.2.91
* add test_n_minus_f_pool_processes_attrib

Fix Attrib txn for a n-f pool, INDY-245

---

setup.py
sovrin_node/server/node.py

Up version of common to 0.3.22 and client to 0.4.24

Up common and client versions

---

scripts/add_keys.py
scripts/load_test.py

They use cryptonyms instead of DID thus cannot work with latest changes
INDY-421

Fix load test script and script for adding keys

---

setup.py
sovrin_client/anon_creds/sovrin_public_repo.py

Fix imports of Tails

---

sovrin_node/__metadata__.py

Also sets __author__ = "Hyperledger"

Release v1.0 (DO NOT MERGE)

---

getting-started.md

Updates to the terminology to reflect current style in text and code. This has been reviewed by Kelly.

INDY-440 Getting Started Guide - New Terminology

---

setup.py

Update plenum version

---

scripts/read_ledger
setup.py
sovrin_node/test/upgrade/test_migration_util.py
sovrin_node/utils/migration_tool.py

INDY-373: fix read-ledger script; increment plenum version

---

sovrin_node/test/upgrade/test_migration_tool.py
sovrin_node/utils/migration_tool.py

Fixed wrong path to python module during dynamic import

Hotfix/migration to 1.1.33 (INDY-808)

---

sovrin_node/test/upgrade/test_migration_tool.py
sovrin_node/utils/migration_tool.py

cherry-picked 43c83dc
* added test for _get_migration_scripts function
* fixed path resolving for python modules

Hotfix/migration to 1.1.33 (INDY-808) (#337)

---

docs/Sovrin_Running_Locally.md

Fix some broken links and adapt the Sovrin_Running_Locally guide to work with the latest version and cover the whole Getting Started scenario.

Rework documentation for local cluster

---

sovrin_client/cli/cli.py
sovrin_client/test/cli/test_send_get_nym_validation.py

- Added functionality to return a role if the nym's role is set.
- Added test to verify that a role value is returned with a GET_NYM
transaction.

INDY-333: add displaying of role for GET_NYM command

---

sovrin_client/test/state_proof/test_state_proof_for_get_requests.py
sovrin_client/test/test_nym_attrib.py
sovrin_common/serialization.py
sovrin_node/server/domain_req_handler.py
sovrin_node/test/state_proof/test_state_proofs_for_get_requests.py

This eliminates issues with client-side formatting

Reformat attr data before saving

---

Jenkinsfile
setup.py

Remove post install; set next version

---

indy_node/server/domain_req_handler.py
indy_node/test/req_handler/test_domain_req_handler.py
indy_node/test/validator_info/test_validator_info.py

INDY-877: protocol version support in indy-node

---

ci/code-validation.dockerfile
ci/ubuntu.dockerfile

combined apt update and install in dockerfile

---

build-scripts/ubuntu-1604/build-indy-node.sh
data/migrations/deb/1_1_37_to_1_1_38.py
data/migrations/deb/helper_1_1_37_to_1_1_38.py

INDY-895: add migration for domain ledger with None values

---

setup.py

increment plenum

---

indy_client/anon_creds/indy_public_repo.py
indy_client/client/wallet/attribute.py
indy_client/client/wallet/node.py
indy_client/client/wallet/pool_config.py
indy_client/client/wallet/upgrade.py
indy_client/client/wallet/wallet.py
indy_common/identity.py
indy_node/test/req_handler/test_domain_req_handler.py
indy_node/test/state_proof/test_state_proofs_for_get_requests.py
setup.py

INDY-877: do not set protocol version be default in Requests

---

data/migrations/deb/helper_1_1_37_to_1_1_38.py

INDY-895: Hot fix newnode2

---

data/migrations/deb/helper_1_1_37_to_1_1_38.py

- check that state files exist before removing them

INDY-895: fix migration

---

scripts/init_bls_keys
setup.py

INDY-906: add init_bls_key into installation

---

getting-started.md

Updates the link to the Vagrant Setup Guide.
Signed-off-by: TechWritingWhiz <techwritingwhiz@gmail.com>

GSG - Updates the link to the Vagrant Setup Guide

---

indy_node/server/node.py
indy_node/server/pool_manager.py
setup.py

INDY-670: support BLS changes from plenum

---

indy_client/test/cli/test_node.py
indy_common/auth.py
indy_common/test/auth/test_auth_error.py

INDY-905: add tests for rotation of BLS keys by Trustee

---

scripts/init_bls_keys

INDY-915: fix paths in init_bls_keys

---

scripts/enable_bls

INDY-883: use 'node_dest' instead of 'node_seed' in 'enable_bls'

---

indy_node/__metadata__.py
indy_node/server/domain_req_handler.py
indy_node/test/state_proof/test_state_proofs_for_get_requests.py
setup.py

Support the following changes in plenum:
do not return state proof if there is no multi-sig for that state
reduce log level for Reply-related messages so that they're not shown in CLI

INDY-915: Support changes in plenum

---

Jenkinsfile.ci

limited time to perform testing

---

indy_common/types.py
setup.py

Add length limit check for version field

---

docs/Indy_Running_Locally.md
getting-started.md

Updated the Getting Started Guide with a link to the new instructions
on how to set up an actual developer environment connected
to a sandbox with Vagrant.
Signed-off-by: TechWritingWhiz <techwritingwhiz@gmail.com>

Gsg update Updated Getting Started Guide with Link

---

indy_node/test/catchup/test_requests_post_new_node_catchup.py
setup.py

Signed-off-by: Victor Muzychenko <mzkvct@gmail.com>

up plenum to 1.2.161

---

indy_client/anon_creds/indy_public_repo.py
indy_client/test/anon_creds/test_public_repo.py
indy_common/types.py

make revocation part in CLAIM_DEF optional

---

indy_node/server/upgrader.py
indy_node/test/upgrade/test_node_upgrade_unsuccessful.py
indy_node/test/upgrade/test_pool_upgrade_no_loop_force_unsuccessful.py
indy_node/test/upgrade/test_pool_upgrade_no_loop_reinstall_unsuccessful.py
indy_node/test/upgrade/test_pool_upgrade_no_loop_unsuccessful.py
indy_node/test/upgrade/test_upgrade_timeout.py
indy_node/utils/node_control_tool.py

- Update log messages
- Guide to look into syslog
- Refactor

Make upgrade logging more verbose

---

build-scripts/ubuntu-1604/postinst_node
data/migrations/deb/1_2_188_to_1_2_189.py

Fix migration and post install in scope of config changes

---

indy_client/__init__.py

Replace .indy with config value in client.__init__

---

docs/indy-running-locally.md
docs/start-nodes.md

Update doc to install/run nodes

---

docs/indy-running-locally.md
docs/start-nodes.md
getting-started.md
scripts/create_dirs.sh

fix documentation/scripts to start pool locally

---

indy_node/test/upgrade/test_node_control_tool.py
setup.py

increment plenum version

---

indy_node/server/node.py
indy_node/server/upgrade_log.py
indy_node/server/upgrader.py
indy_node/test/upgrade/helper.py
indy_node/test/upgrade/test_node_upgrade.py
indy_node/test/upgrade/test_node_upgrade_in_progress.py
indy_node/test/upgrade/test_node_upgrade_in_progress_no_protocol_version.py
indy_node/test/upgrade/test_node_upgrade_no_protocol_version.py
indy_node/test/upgrade/test_node_upgrade_rescheduled_view_change.py

fix issues with upgrade:
- do not send protocol version with NODE_UPGRADE txns
- do not reschedule the same upgrade
- do not re-send NODE_UPGRADE after each view change

INDY-953: Fix protocol version upgrade

---

indy_client/test/state_proof/test_state_proof_for_get_requests.py
indy_common/state/domain.py

fix state proof verification when submitter is not the same person as reader

INDY-954: verification of state proof by client fix

---

setup.py

Next plenum

---

data/migrations/deb/1_2_44_to_1_2_45.py

Add client genesis txns migration

---

data/migrations/deb/1_2_188_to_1_2_189.py

Add genesis txn to client folder during migration

---

Jenkinsfile.ci
ci/build_base_image.sh
ci/ubuntu.dockerfile
docker-files/baseimage/Makefile
docker-files/baseimage/indy-baseci.ubuntu.dockerfile
docker-files/baseimage/indy-baseimage.ubuntu.dockerfile
docker-files/baseimage/indy-core-baseci.ubuntu.dockerfile
docker-files/baseimage/indy-core-repo.preferences
docker-files/baseimage/scripts/charm_crypto.sh
docker-files/baseimage/scripts/clean.sh
docker-files/baseimage/scripts/libindy.sh
docker-files/baseimage/scripts/user.sh
setup.py

[INDY-945, INDY-900, INDY-530] hierarchy of docker images, docker build automation via make, test env setup

---

docker-files/baseimage/.dockerignore

adding .dockerignore to clarify docker context for base image build routine

---

.flake8
scripts/validator-info

Change default path to handle network name

---

dev-setup/ubuntu/init-dev-project.sh
dev-setup/ubuntu/setup-dev-depend-ubuntu14.sh
dev-setup/ubuntu/setup-dev-depend-ubuntu16.sh
dev-setup/ubuntu/setup-dev-python.sh
docs/setup-dev.md

Update for docs and setup scripts to install libindy into dev environment

---

setup.py

INDY-878: update plenum dependency to 1.2.192.

---

setup.py

bump plenum

---

indy_node/test/helper.py

Signed-off-by: Lovesh <lovesh.harchandani@evernym.com>

remove methods from spyables list

---

runner.py

Fix runner.py to handle errors

---

indy_common/test/types/test_claim_def_get_schema.py
indy_common/types.py
indy_node/test/validator_info/test_validator_info.py

INDY-114: use IdentifierField for ORIGIN validation in GET_CLAIM_DEF

---

data/migrations/deb/1_2_233_to_1_2_234.py
indy_common/config_helper.py
indy_common/config_util.py
indy_node/general_config/ubuntu_platform_config.py
indy_node/server/node.py
scripts/validator-info
setup.py

Also increment plenum version.

Fix validator info placement, implement migration of nodes data.

---

scripts/create_dirs.sh

INDY-878: fix scripts/create_dirs.sh.

---

build-scripts/ubuntu-1604/postinst_node

[INDY-986] Config nofile limit for indy-node service

---

README.md

improve How-to-send-PR docs

---

setup.py

[INDY-948] Increase plenum version

---

indy_client/cli/cli.py
indy_client/test/anon_creds/test_public_repo.py
indy_client/test/cli/constants.py
indy_client/test/cli/test_send_claim_def.py
indy_client/test/cli/test_send_schema.py
indy_node/server/domain_req_handler.py

forbid creation of a Schema with existent NAME and VERSION sine a Schema needs to be identified by seqNo

INDY-1035: forbid creation of a Schema with existent NAME and VERSION

---

Jenkinsfile.ci

Do not fail if workspace cleanup step fails due to not installed plugin

---

indy_client/test/cli/test_z_accept_invitation_hex_as_pubkey.py
setup.py

Plenum v 215

---

indy_client/test/cli/test_z_accept_invitation_hex_as_pubkey.py

fix test on Jenkins

---

environment/vagrant/training/IndyCluster-master/scripts/validator.sh
environment/vagrant/training/vb-multi-vm/scripts/validator.sh

[INDY-1046] Change path for indy_config.py and indy.env to /etc/indy

---

build-scripts/ubuntu-1604/postinst_node
docs/start-nodes.md
scripts/setup_indy_node_iptables
scripts/setup_iptables
setup.py

INDY-1087: re-organise indy iptables scripts for ease of use.

---

docs/setup-iptables.md
docs/start-nodes.md

INDY-1087: add separate docs/setup-iptables.md file with instructions.

---

setup.py

Next plenum version

---

environment/docker/pool/client.ubuntu.dockerfile
environment/docker/pool/core.ubuntu.dockerfile
environment/docker/pool/node.init.ubuntu.dockerfile

Make some config fixes in docker; add libindy to client container

---

indy_node/server/config_req_handler.py
indy_node/server/upgrader.py
indy_node/test/upgrade/test_upgrade_pool_with_demoted_nodes.py
setup.py

Check that demoted node should not be included to the upgrade schedule

---

scripts/setup_iptables

The following features were added:
- logging of rejected connections;
- checking for rule existance before appending.

INDY-1087: add improvements for setup_iptables script.

---

docs/ci-cd.md

[INDY-1088] Improve docs about build processes

---

indy_client/test/cli/conftest.py
indy_client/test/cli/test_nym.py
indy_client/test/cli/test_nym_suspension.py
indy_node/server/domain_req_handler.py
indy_node/test/conftest.py
indy_node/test/nym_txn/test_nym_resend.py
indy_node/test/suspension/test_suspension.py

INDY-1069: move state-depended checks from static to dynamic validation.

---

indy_client/test/cli/conftest.py
indy_client/test/cli/test_send_get_nym_validation.py
indy_client/test/conftest.py
indy_client/test/test_nym_attrib.py
indy_common/types.py
indy_common/util.py
indy_node/server/client_authn.py
indy_node/server/domain_req_handler.py
indy_node/server/node.py
indy_node/test/conftest.py
indy_node/test/replay/test_successive_batch_no_state_change.py
setup.py

Signed-off-by: Lovesh <lovesh.harchandani@evernym.com>

changes as per new plenum

---

scripts/generate_indy_pool_transactions

[INDY-1072] Disable logs for generating indy pool transactions

---

README.md
data/migrations/README.md
docs/pool-upgrade.md

Pool Upgrade docs

---

environment/vagrant/training/vb-multi-vm/scripts/agent.sh
environment/vagrant/training/vb-multi-vm/scripts/validator.sh

[INDY-1109] Added NETWORK_NAME into config after install indy-node

---

indy_client/cli/cli.py
indy_client/cli/command.py
indy_client/cli/constants.py
indy_client/client/client.py
indy_client/client/wallet/attribute.py
indy_client/client/wallet/wallet.py
indy_client/test/cli/test_send_attrib_validation.py
indy_client/test/cli/test_send_get_attr.py
indy_common/state/domain.py
indy_common/test/types/test_attrib.py
indy_common/test/types/test_attrib_schema.py
indy_common/test/types/test_get_attrib_schema.py
indy_common/types.py
indy_node/server/domain_req_handler.py
setup.py

INDY-1074: add ATTRIB hash and enc support, fix and unskip tests.

---

docs/requests.md
docs/transactions.md

INDY-1074: update docs.

---

setup.py

[INDY-1150] Increase plenum version

---

indy_node/test/upgrade/helper.py
setup.py

INDY-1151: update plenum version.

---

indy_client/agent/agent_net.py
indy_client/agent/endpoint.py
indy_client/client/client.py
indy_client/test/agent/base_agent.py
indy_client/test/agent/conftest.py
indy_common/config.py
setup.py

[INDY-1057] Getting rid of raet stuff

---

setup.py

increment version of plenum

---

setup.py

Increment plenum version for 1.3.54-rc

---

runner.py

Check test suit preparation exit status

---

ci/ubuntu.dockerfile
indy_node/test/nym_txn/test_nym_resend.py
setup.py

Indy SDK version integration

---

environment/vagrant/training/vb-multi-vm/TestIndyClusterSetup.md

INDY-1181: Suggest amd64 arch for packer build / fix box name (with sign-off)

---

setup.py

INDY-1112: update plenum version.

---

design/anoncreds.md

Added ":" as a field separator

---

design/validator_info.md

Version 1 of validator_info design

---

indy_common/constants.py
indy_common/test/types/test_get_revoc_reg_def_schema.py
indy_common/transactions.py
indy_common/types.py
indy_node/server/client_authn.py
indy_node/server/domain_req_handler.py
indy_node/test/anon_creds/conftest.py
indy_node/test/anon_creds/test_get_revoc_reg_def_send.py

[INDY-1135] Added GET_REVOC_REG_DEF transaction

---

setup.py

update plenum version to 1.2.264

INDY-1148 : update plenum version

---

design/anoncreds.md

Change type to revocDefType for Revocation related messages

---

indy_common/constants.py
indy_common/state/domain.py
indy_common/test/types/test_get_revoc_reg_def_schema.py
indy_common/test/types/test_revoc_def_entry_submit_schema.py
indy_common/test/types/test_revoc_def_submit_schema.py
indy_common/types.py
indy_node/server/domain_req_handler.py
indy_node/server/revocation_strategy.py
indy_node/test/anon_creds/conftest.py
indy_node/test/anon_creds/test_get_revoc_reg_def_send.py

[REVOC-TYPE] Added REVOC_TYPE and fixed tests

---

indy_client/test/anon_creds/test_schema.py
indy_node/server/domain_req_handler.py

- Added validation of field 'attr_names'
- Added test for it

INDY-1169 : Added static validation of schema

---

indy_node/test/replay/test_successive_batch_no_state_change.py
setup.py

[INDY-1185] Fixed some failing tests in hyperledger jenkins

---

Jenkinsfile.cd
indy_node/server/plugin/agent_authz/authz_checker.py
indy_node/server/plugin/agent_authz/domain_req_handler.py
indy_node/utils/node_runner.py
setup.py

[WIP] Pipelines for authz branches

---

indy_node/general_config/general_config.py
indy_node/general_config/ubuntu_platform_config.py

[INDY-1221] Disable stdout logging after install package

---

indy_common/auth.py
indy_common/test/auth/test_auth_claim_def.py
indy_common/test/auth/test_auth_error.py
indy_common/test/auth/test_auth_node.py
indy_common/test/auth/test_auth_nym.py
indy_common/test/auth/test_auth_pool_config.py
indy_common/test/auth/test_auth_pool_upgrade.py
indy_common/test/auth/test_auth_schema.py
indy_node/server/config_req_handler.py
indy_node/server/domain_req_handler.py
indy_node/server/pool_req_handler.py

INDY-1111: Refactoring

---

indy_client/test/cli/conftest.py
indy_client/test/cli/test_node.py
setup.py

Changes for bls key. New plenum version

---

ci/ubuntu.dockerfile
indy_common/config.py
indy_node/server/node.py
setup.py

Also added rocksdb-related stuff.

INDY-1205: make stateTsStorage type configurable, set rocksdb by default.

---

design/anoncreds.md

Added additional info about processing REVOC_REG_ENTRY

---

indy_client/test/conftest.py
indy_node/test/attrib_txn/test_n_minus_f_pool_processes_attrib.py
indy_node/test/conftest.py

[INDY-1058] Get rid of Registry-based pools

---

setup.py

Bump plenum.

---

build-scripts/ubuntu-1604/build-indy-node.sh
environment/vagrant/sandbox/DevelopmentEnvironment/Virtualbox/Vagrantfile
environment/vagrant/sandbox/SandboxAgents/scripts/agent.sh
environment/vagrant/training/IndyCluster-master/scripts/agent.sh
environment/vagrant/training/IndyCluster-master/scripts/validator.sh
environment/vagrant/training/vb-multi-vm/scripts/agent.sh
environment/vagrant/training/vb-multi-vm/scripts/validator.sh

[INDY-1218] Added libsodium18 as dependency for indy-node package

---

ci/ubuntu.dockerfile
setup.py

[INDY-1206] Remove test repo from ci and increment plenum

---

indy_common/test/types/test_get_revoc_reg_def_schema.py
indy_common/types.py
indy_node/server/revocation_strategy.py
indy_node/test/anon_creds/conftest.py
indy_node/test/anon_creds/test_get_revoc_reg_def_send.py
indy_node/test/anon_creds/test_revoc_reg_entry_validation.py
indy_node/test/anon_creds/test_state_proof_for_get_request.py
setup.py

[INDY-1137] Remove REVOC_TYPE from GET_REVOC_REG_DEF query

---

indy_node/server/domain_req_handler.py

[INDY-1137] Fix optional ISSUED and REVOKED for GET_REVOC_REG_DELTA

---

indy_common/state/domain.py
indy_node/server/domain_req_handler.py

[INDY-1137] Remove DID from path to REVOC_REG_ENTRY

---

indy_node/server/domain_req_handler.py

[INDY-1137] Fix when REVOC_REG_ENTRY for from not found

---

indy_node/server/domain_req_handler.py

[INDY-1137] change revoc_reg_def_id in reply for GET_REVOC_REG_DELTA

---

indy_node/server/domain_req_handler.py

[INDY-1137] Fix situation, when timestamp found but rev_reg_entry not

---

indy_common/state/domain.py
indy_node/server/domain_req_handler.py
indy_node/test/anon_creds/conftest.py
indy_node/test/anon_creds/test_revoc_def_validation.py

[INDY-1264] Markers for revocation transactions are string now

---

environment/openshift/README.md
environment/openshift/scripts/client/start.sh
scripts/indy

Changes:
- added message about new getting started in readme
- added message about new getting started in start of old cli script

INDY-1226: deprecations old python cli

---

README.md
getting-started.md

changes:
- change link in readme
- add warning in the old getting started

INDY-1228: change documentation of old GSG

---

acceptance/AS-03-01-identity-owner.batch
acceptance/AS-03-01-steward.batch
acceptance/AS-03-01-trust-anchor.batch
acceptance/AS-03-01-trustee.batch

Add batches for acceptance testing

---

ci/code-validation.dockerfile
environment/docker/baseimage/indy-baseimage.ubuntu.dockerfile
environment/docker/pool/core.ubuntu.dockerfile
environment/openshift/core.ubuntu.dockerfile

changes:
-added version 9.0.3 of the library pip, because pip released version 10.0.0

INDY-1272: added version to pip

---

design/anoncreds.md

[design-revocation] Revoked and prev_accum are optional now

---

indy_node/server/node.py
indy_node/server/pool_manager.py
indy_node/test/nym_txn/test_nym_resend.py
indy_node/utils/node_runner.py
setup.py

get rid of RegistryPoolManager

---

scripts/read_ledger

INDY-1284: add conversion of read_ledger's 'from' and 'to' to int.

---

docs/node-monitoring-tools-for-stewards.md
setup.py

INDY-1251: fix node-monitoring-tools-for-stewards.md

---

scripts/read_ledger
setup.py

INDY-1284: add check for None of 'from' and 'to' params of read_ledger.

---

environment/docker/pool/README.md

In "Prerequisites section, change "used" to "user"

INDY-1285: Update README typo

---

indy_node/test/helper.py
indy_node/test/suspension/test_suspension.py
indy_node/test/upgrade/test_node_schedules_upgrade_after_pool_ledger_update.py
indy_node/test/upgrade/test_upgrade_pool_with_demoted_nodes.py
setup.py

Plenum version 328

---

scripts/ansible/pool_get_logs.yml
scripts/ansible/pool_install.yml
scripts/ansible/pool_uninstall.yml
scripts/ansible/pool_update_config.yml

Add ansible playbooks for test pool [skip ci]

---

environment/vagrant/training/vb-multi-vm/TestIndyClusterSetup.md

Changes:
- added warning about old client in TestIndyClusterSetup.md
- changed links from old GSG to new GSG

INDY-1184: add warning about old client in TestIndyClusterSetup.md

---

setup.py

[Bump plenum] Bump plenum version (base58)

---

build-scripts/ubuntu-1604/build-3rd-parties.sh
setup.py

[INDY-1291] Freeze packages version

---

setup.py

[Pygments-fix] bump plenum version

---

setup.py

[Pygments] bump plenum

---

setup.py

[pygments] bump plenum version

---

scripts/ansible/pool_install.yml
scripts/ansible/pool_uninstall.yml

Improve ansible playbooks for test pool

---

docs/setup-dev.md
docs/start-nodes.md

Signed-off-by: ryanwest6 <31378238+ryanwest6@users.noreply.github.com>

Fixed typos and added punctuation for some docs

---

indy_node/test/helper.py
indy_node/test/validator_info/test_validator_info.py
setup.py

[Test purpose] disable dumping validator-info for tests

---

environment/docker/getting_started_turnkey/Makefile
environment/docker/getting_started_turnkey/README
environment/docker/getting_started_turnkey/README.md
environment/docker/getting_started_turnkey/indy-base-dockerfile
environment/docker/getting_started_turnkey/indy-cli

Add a turnkey, Docker-based sandbox that enables quick and easy exploration of Hyperledger Indy concepts. This devops repo can be used to gather hands-on experience of Indy basics using the scenarios outlined in the Sovrin's Getting Started Guide.

INDY-1207: Add Docker getting started configuration

---

data/migrations/deb/1_3_396_to_1_3_397.py

[INDY-1244] Convert bytearray from leveldb into bytes for rocksdb

---

setup.py

[Bump plenum] bump plenum version

---

scripts/read_ledger

[INDY-1289] Remove Ledger init and init only storage

---

setup.py

Bump plenum version

---

setup.py

[Hotfix libindy] bump plenum

---

build-scripts/ubuntu-1604/postinst_node

[Hotfix stable] Hotfix for arg parsing to systemd and supervisord

---

build-scripts/ubuntu-1604/postinst_node

[INDY-1330] Hotfix for arg parsing to systemd and supervisord

---

scripts/validator-info
setup.py

was done:
-  node's and client's port displaying
- duplicate displaying for all info in verbose mode
- added n/a if value is empty

[INDY-1175] validator-info fixes

---

docs/node-monitoring-tools-for-stewards.md
setup.py

INDY-1251: extend spikes documentation, bump plenum.

---

setup.py

[INDY-1175] bump plenum

---

indy_node/test/persistence/test_idr_cache_update_after_catchup.py

Fix persistence tests

---

indy_node/server/config_req_handler.py

Fix pool_config tests

---

indy_node/server/domain_req_handler.py

Signed-off-by: Lovesh Harchandani <lovesh.bond@gmail.com>

avoid generating state proofs during txn validation

---

indy_common/constants.py
indy_common/state/domain.py
indy_node/server/domain_req_handler.py
indy_node/server/revocation_strategy.py
indy_node/test/anon_creds/conftest.py
indy_node/test/anon_creds/helper.py
indy_node/test/anon_creds/test_get_revoc_reg_delta_send_by_demand.py
indy_node/test/anon_creds/test_state_proof_for_get_request.py

INDY-1319: Fix anoncred's tests

---

indy_node/server/action_req_handler.py
indy_node/server/config_req_handler.py
indy_node/test/anon_creds/conftest.py
indy_node/test/anon_creds/test_get_revoc_reg_delta_unit.py

INDY-1319: fix usage of reqToTxn().

---

indy_node/server/config_req_handler.py

INDY-1319: fix apply() function of config_req_handler.

---

indy_common/state/domain.py

[INDY-1319] fix txn corruption

---

indy_client/anon_creds/indy_public_repo.py

Fix client anon_cred tests

---

design/validator_info.md
indy_common/auth.py
indy_common/test/auth/test_auth_validator_info.py
indy_node/server/action_req_handler.py
indy_node/test/pool_restart/test_fail_pool_restart.py
indy_node/test/validator_info/test_validator_info_command.py

Changes:
- added check to client role
- added tests for auth check role
- added test for request with incorrect role
- update documentation

[WIP][INDY-1363] add permission to validator_info command only for trustee and steward

---

indy_client/cli/cli.py
indy_client/test/cli/conftest.py
indy_client/test/cli/helper.py

[INDY-1319] txn-refactoring in cli dir

---

indy_node/utils/node_control_tool.py

[INDY-1323] Hold libindy-crypto

---

scripts/validator-info

[INDY-1310] Set owner of log file and small fixes in stdout logging

---

scripts/read_ledger

[INDY-1318] Fix --network option for read_ledger

---

build-scripts/ubuntu-1604/postinst_node
data/migrations/deb/1_3_433_to_1_3_434.py
docs/indy-running-locally.md
docs/start-nodes.md
environment/docker/getting_started_turnkey/Makefile
environment/docker/getting_started_turnkey/README.md
environment/docker/pool/node.init.ubuntu.dockerfile
environment/openshift/scripts/common/initialize.sh
environment/openshift/scripts/node/start.sh
environment/vagrant/training/IndyCluster-master/scripts/validator.sh
environment/vagrant/training/IndyCluster-master/scripts/validator01.sh
environment/vagrant/training/IndyCluster-master/scripts/validator02.sh
environment/vagrant/training/IndyCluster-master/scripts/validator03.sh
environment/vagrant/training/IndyCluster-master/scripts/validator04.sh
environment/vagrant/training/vb-multi-vm/scripts/validator.sh
indy_node/utils/node_runner.py
scripts/install_indy_node.bat
scripts/running_locally/setupEnvironment.sh
scripts/start_indy_node

Also added migration script that appends node and client IPs to indy env file.

INDY-1332: support different IPs for node and client listeners.

---

setup.py

INDY-1332: bump plenum.

---

data/migrations/deb/1_3_433_to_1_3_434.py
environment/docker/pool/node.init.ubuntu.dockerfile
environment/docker/pool/node_build.sh
environment/docker/pool/pool_build.sh

INDY-1332: fix docker files.

---

setup.py

[INDY-1332] Bump plenum

---

data/migrations/deb/1_3_433_to_1_3_434.py

INDY-1332: add client/node IPs to env file if they are not present.

---

scripts/validator-info

Signed-off-by: Axel Nennker <axel.nennker@telekom.de>
when validator-info is called with option --nagios then now Nagios compatible output is generated

added --nagios option to produce Nagios output

---

environment/docker/pool/pool_build.sh
setup.py

INDY-1332: set 0.0.0.0 for listeners of docker pool nodes.

---

data/migrations/deb/1_3_428_to_1_3_429.py

[FIX migration] remove encode for seq_no

---

data/migrations/deb/1_3_428_to_1_3_429.py

INDY-1327: change digest format in migration 1_3_428_to_1_3_429.py

INDY-1327: change digest format in migration seq_no_db and txn 

---

scripts/ansible/pool_get_logs.yml

Fetch journalctl logs using ansible

---

docs/1.3_to_1.4_migration_guide.md

[INDY-1392] Add migration guide

---

docs/requests.md
docs/transactions.md

Update docs for a new tag parameter in CLAIM_DEF

---

setup.py

Signed-off-by: Devin Fisher <devin.fisher@evernym.com>

repin to pickup a fix in plenum

---

indy_common/config.py
indy_node/server/node.py
scripts/read_ledger
setup.py

Also modified read_ledger tool so that it does not create LOG files
in case of RocksDB used.

INDY-1245: support RocksDB storages configuration.

---

docs/1.3_to_1.4_migration_guide.md

[INDY-1392] Gramma fix

---

scripts/ansible/pool_get_logs.yml

Fetch node info from pool in ansible playbook

---

setup.py

INDY-1390: bump plenum.

---

ci/ubuntu.dockerfile
indy_client/test/conftest.py
indy_node/test/conftest.py
indy_node/test/pool_restart/test_pool_restart.py
indy_node/test/validator_info/test_validator_info_command.py

Changes:
- update restart tests
- update validator-info tests
- add wrappers on sdk restart and get_validator_info functions
- update libindy version

[WIP][ci skip] Integration of the latest SDK

---

setup.py
tools/diagnostics/nsdiff
tools/diagnostics/nsreplay

Add ns* scripts to the script list in setup.py. This will add the scripts to the Debian file.

Ns replay tweeks

---

scripts/performance/perf_processes.py

Update per_processes.py to handle perfomance testing needs

---

indy_node/server/domain_req_handler.py
setup.py

Add missed txnId

---

docs/requests.md
docs/transactions.md
indy_node/test/api/helper.py
indy_node/test/api/test_attrib_reply.py
indy_node/test/api/test_claim_def_reply.py
indy_node/test/api/test_nym_reply.py
indy_node/test/api/test_schema_reply.py
indy_node/test/txns/test_replies.py
scripts/performance/perf_processes.py

Tests for reply structure

---

docs/process-based-load-script.md
scripts/performance/perf_processes.py

Fix flake errors

---

data/migrations/deb/1_3_428_to_1_3_429.py

[Fix migration] fix revoc_reg_def_id building

---

data/migrations/deb/1_3_428_to_1_3_429.py

[Migration] Fix seq_no_db moving

---

docs/1.3_to_1.4_migration_guide.md

[Migration Guide] add cli-upgrading steps

---

setup.py

[RC-1.4.65] bump plenum version

---

indy_node/__init__.py
indy_node/utils/node_runner.py
setup.py

Signed-off-by: lovesh harchandani <lovesh.bond@gmail.com>

bump plenum version and update plenum code

---

docs/process-based-load-script.md

Fix example for perf_processes.py

---

setup.py

[INDY-1385] bump plenum

---

data/migrations/deb/1_3_428_to_1_3_429.py
scripts/validator-info

Changes:
-  For now --json option returns completely parsable JSON.
- Also, --json options returns all acceptable info (highest verbosity).
- Fix errors if node_info files are empty.

[INDY-1443] fix --json behaviour

---

indy_node/persistence/idr_cache.py
indy_node/server/restarter.py
indy_node/utils/node_control_tool.py
setup.py

Change log levels

---

scripts/validator-info

[INDY-1443] json dumps as output with --json option

---

indy_client/agent/agent.py
indy_client/test/cli/conftest.py
indy_client/test/cli/helper.py
setup.py

INDY-1467: bump plenum.

---

setup.py

[INDY-1462] bump plenum version

---

docs/setup-dev.md

Signed-off-by: fabienpe <fabienpe@users.noreply.github.com>

Corrected instruction to match actual file name.

---

setup.py

Bumps plenum version to 1.4.461

---

indy_node/__metadata__.py
setup.py

[Bump version] bump version to 1.5

---

tools/diagnostics/nsdiff
tools/diagnostics/nsreplay

Signed-off-by: Corin Kochenower <corin.kochenower@evernym.com>

Node State tools/scripts require python 3

---

indy_node/server/node.py

Add warning when going to restart due to inconsistent 3PC state

---

setup.py

[INDY-1470] bump plenum version

---

setup.py

[INDY-1468] bump plenum version

---

setup.py

INDY-1496: bump plenum.

---

scripts/client_connections/README.md
scripts/client_connections/just_connect_N_times.py

INDY-1431: modify and improve clients connections system test and doc.

---

scripts/performance/perf_processes.py

Add requeired ars

---

docs/transactions.md

Signed-off-by: Alexey Abel <dev@abelonline.de>

Fix grammar, wording, typos and add a link

---

setup.py

[INDY-1478] bump plenum version

---

acceptance/indy-cli-batches/AS-04-02-after-upgrade.batch
acceptance/indy-cli-batches/AS-04-02-before-upgrade.batch
acceptance/indy-cli-batches/expected/AS-04-02-after-upgrade.expected
acceptance/indy-cli-batches/expected/AS-04-02-before-upgrade.expected

add tags to cred-def txns

---

scripts/get_metrics

[WIP] INDY-1475: First version of statistics processing script

---

setup.py

INDY-1531: bump plenum.

---

acceptance/indy-cli-batches/AS-01-01-general-1.batch
acceptance/indy-cli-batches/AS-01-01-general-2.batch
acceptance/indy-cli-batches/AS-01-01-general-3.batch
acceptance/indy-cli-batches/AS-01-02-before-migration-1.batch
acceptance/indy-cli-batches/AS-01-02-before-migration-2.batch
acceptance/indy-cli-batches/AS-01-02-before-migration-3.batch
acceptance/indy-cli-batches/AS-02-01-invalid-cases.batch
acceptance/indy-cli-batches/AS-02-01-prepare-DIDs.batch
acceptance/indy-cli-batches/AS-02-02-invalid-cases.batch
acceptance/indy-cli-batches/AS-03-01-identity-owner.batch
acceptance/indy-cli-batches/AS-03-01-steward.batch
acceptance/indy-cli-batches/AS-03-01-trust-anchor.batch
acceptance/indy-cli-batches/AS-03-01-trustee.batch
acceptance/indy-cli-batches/AS-04-02-before-upgrade.batch
acceptance/indy-cli-batches/expected/AS-01-01-general-1.expected
acceptance/indy-cli-batches/expected/AS-01-01-general-2.expected
acceptance/indy-cli-batches/expected/AS-01-01-general-3.expected
acceptance/indy-cli-batches/expected/AS-01-02-before-migration-1.expected
acceptance/indy-cli-batches/expected/AS-01-02-before-migration-2.expected
acceptance/indy-cli-batches/expected/AS-01-02-before-migration-3.expected
acceptance/indy-cli-batches/expected/AS-02-01-invalid-cases.expected
acceptance/indy-cli-batches/expected/AS-02-01-prepare-DIDs.expected
acceptance/indy-cli-batches/expected/AS-02-02-invalid-cases.expected
acceptance/indy-cli-batches/expected/AS-03-01-identity-owner.expected
acceptance/indy-cli-batches/expected/AS-03-01-steward.expected
acceptance/indy-cli-batches/expected/AS-03-01-trust-anchor.expected
acceptance/indy-cli-batches/expected/AS-03-01-trustee.expected
acceptance/indy-cli-batches/expected/AS-04-02-before-upgrade.expected

fix compatibility with SDK 1.6.1

---

scripts/get_metrics
setup.py

INDY-1475: Bump plenum version

---

indy_common/config.py
indy_node/test/upgrade/test_node_control_tool_resolves_dep_top_level.py
indy_node/test/upgrade/test_node_control_tool_resolves_dependencies.py
indy_node/test/upgrade/test_upgrade_top_level_config_not_set.py
indy_node/test/upgrade/test_upgrade_top_level_def_cfg.py
indy_node/test/upgrade/test_upgrade_top_level_ext_pkg.py
indy_node/utils/node_control_tool.py

Upgrade node_control_tool to allow upgrade different upper level packet

---

indy_client/test/cli/test_agent_cli2.py
indy_client/test/cli/test_tutorial_manual.py
setup.py

Plenum 485

---

README.md

Signed-off-by: nbzeman@gmail.com

Update README.md to read The Sovrin Foundation in descriptors

---

docs/write-code-guideline.md

Signed-off-by: brendafrancis <brenda.francis@evernym.com>

removed extra space

---

scripts/performance/perf_processes.py

Make methods empty to stop write ops during read reqs

---

setup.py

[INDY-1555] bump plenum version

---

indy_node/__metadata__.py

[Bump node] bump indy-node version

---

setup.py

[INDY-1562] bump plenum version

---

scripts/read_ledger

INDY-1558: Reformat read_ledger txn message

---

scripts/ansible/indy_config_default.py
scripts/ansible/pool_install.yml

fix compatibility with brand new pool

---

scripts/build_graph_from_csv

INDY-1543: Improve build_graph_from_csv script

---

setup.py

INDY-1564: increment plenum version

---

setup.py

INDY-1389: increment plenum version

---

setup.py

[INDY-1595] bump plenum version

---

scripts/performance/config_perf_spike_load.yml
scripts/performance/perf_spike_load.py

Signed-off-by: NataliaDracheva <natalia.dracheva@dsr-corporation.com>

[INDY-1567] Added load script for complex load testing with spikes.  

---

scripts/get_metrics
setup.py

INDY-1602: Bug fixes

---

scripts/performance/config_perf_spike_load.yml
scripts/performance/perf_spike_load.py

- Added path expansions;
- updated a config file default values and added a description;
- added information about script parameters and execution mode.

[Indy-1567] Minor fixes and improvements.

---

docs/process-based-load-script.md
scripts/performance/perf_processes.py

- Corrected payment plugin initialization.
- Updated the manual.

INDY-1358: Payment txns in load test script

---

scripts/build_graph_from_csv
setup.py

INDY-1602: Improve build_graph_from_csv and bump plenum version

---

setup.py

INDY-1565: bump plenum.

---

README.md
docs/add-node.md

Add "Node addition" help partition

---

indy_node/test/catchup/test_batch_rejected_and_later_ordered_on_catchup.py
indy_node/test/catchup/test_requests_post_multiple_new_nodes.py
indy_node/test/catchup/test_requests_post_new_node_catchup.py
setup.py

[WIP] Bump plenum version

---

docs/add-node.md

INDY-1522: Add info about base58 verkey

---

indy_node/test/catchup/test_batch_rejected_and_later_ordered_on_catchup.py

Trying to fix some intermittent tests

---

setup.py

[INDY-1642] bump plenum version

---

setup.py

Bump plenum 1.6.538

---

scripts/validator-info-history

INDY-1637: add fixes and printing improvements.

---

setup.py

INDY-1599: bump plenum.

---

setup.py

Bump plenum 1.6.541

---

pool_automation/roles/aws_manage/molecule/default/molecule.yml
pool_automation/roles/common/molecule/default/molecule.yml
pool_automation/roles/common/yamllint
pool_automation/roles/node_install/molecule/default/molecule.yml
pool_automation/roles/pool_install/molecule/default/molecule.yml

Fix tests for pool automation (add missing file)

---

scripts/build_graph_from_csv

Improve build_graph_from_csv

---

scripts/current_validators

Added --protocolVersion flag, 1 = indy-node 1.3, 2 = 1.6
Signed-off-by: evelynevergreene <evelyn.evergreene@evernym.com>

Added changes to reflect updated protocol versions

---

scripts/build_graph_from_csv
scripts/get_metrics

Metrics processing improvements

---

indy_client/cli/constants.py
indy_client/test/cli/test_send_nym_validation.py
indy_common/auth.py
indy_common/constants.py
indy_common/roles.py
indy_common/test/auth/conftest.py
indy_common/test/auth/test_auth_claim_def.py
indy_common/test/auth/test_auth_nym.py
indy_common/test/auth/test_auth_pool_config.py
indy_common/test/auth/test_auth_pool_upgrade.py
indy_common/test/auth/test_auth_schema.py
indy_common/test/test_roles.py
indy_node/persistence/idr_cache.py
indy_node/test/suspension/test_suspension.py

INDY-798: Remove TGB from codebase

---

dev-setup/osx/setup-dev-dependencies.sh

This PR contains a script which installs dev dependencies for OSX

Added script for setting dev dependencies for OSX

---

pool_automation/roles/aws_manage/defaults/main.yml
pool_automation/roles/aws_manage/library/stateful_set.py
pool_automation/roles/aws_manage/library/test_stateful_set.py
pool_automation/roles/aws_manage/tasks/main.yml
pool_automation/roles/aws_manage/tasks/post_down.yml
pool_automation/roles/aws_manage/tasks/pre_up.yml
pool_automation/roles/aws_manage/templates/hosts.j2
pool_automation/roles/aws_manage/templates/ssh_config.j2

[PoC] INDY-1622: Make pool_create usable across AWS regions

---

setup.py

[rc-1.6.77] down version of indy-plenum (for upgrade purposes)

---

acceptance/indy-cli-batches/expected/AS-01-01-general-1.expected
acceptance/indy-cli-batches/expected/AS-01-01-general-2.expected
acceptance/indy-cli-batches/expected/AS-01-01-general-3.expected
acceptance/indy-cli-batches/expected/AS-01-02-after-migration-1.expected
acceptance/indy-cli-batches/expected/AS-01-02-after-migration-2.expected
acceptance/indy-cli-batches/expected/AS-01-02-after-migration-3.expected
acceptance/indy-cli-batches/expected/AS-01-02-before-migration-1.expected
acceptance/indy-cli-batches/expected/AS-01-02-before-migration-2.expected
acceptance/indy-cli-batches/expected/AS-01-02-before-migration-3.expected
acceptance/indy-cli-batches/expected/AS-02-01-invalid-cases.expected
acceptance/indy-cli-batches/expected/AS-02-01-prepare-DIDs.expected
acceptance/indy-cli-batches/expected/AS-02-02-invalid-cases.expected
acceptance/indy-cli-batches/expected/AS-03-01-identity-owner-anyone-can-write.expected
acceptance/indy-cli-batches/expected/AS-03-01-identity-owner.expected
acceptance/indy-cli-batches/expected/AS-03-01-steward.expected
acceptance/indy-cli-batches/expected/AS-03-01-trust-anchor.expected
acceptance/indy-cli-batches/expected/AS-03-01-trustee.expected
acceptance/indy-cli-batches/expected/AS-04-02-after-upgrade.expected
acceptance/indy-cli-batches/expected/AS-04-02-before-upgrade.expected

Signed-off-by: NataliaDracheva <natalia.dracheva@dsr-corporation.com>

Fixed characters in indy-cli output files used for acceptance testing.

---

indy_node/utils/node_control_tool.py

[Hotfix from stable] add libindy-crypto into DEPS list

---

scripts/current_validators

Signed-off-by: Mike Bailey <mike.bailey@evernym.com>

Fix incorrect shell-bang and argparse action

---

indy_node/test/memory_debugging/test_memory_debugging.py

INDY-1723: Tests for memory debugging

---

indy_node/utils/node_control_tool.py

Restore hold_ext param in node controll tool init func

---

setup.py

Plenum v 571

---

setup.py

INDY-1775: bump plenum.

---

scripts/get_metrics

Support BinaryFileStore in get_metrics

---

indy_node/test/upgrade/helper.py
indy_node/test/upgrade/test_get_deps_with_filter.py
indy_node/test/upgrade/test_node_control_tool_resolves_dep_top_level.py
indy_node/test/upgrade/test_node_control_tool_resolves_dependencies.py
indy_node/test/upgrade/test_version_parsing.py
indy_node/utils/node_control_tool.py
indy_node/utils/node_control_utils.py

Change dependency builder to speedup process

---

indy_client/test/cli/test_node_suspension.py

INDY-133: Test testSuspendNodeWhichWasNeverActive enabled

---

setup.py

Plenum v580

---

setup.py

[INDY-1687] bump plenum

---

indy_node/utils/node_control_tool.py
indy_node/utils/node_control_utils.py

Fix external process call

---

scripts/performance/perf_load/perf_gen_req_parser.py
scripts/performance/perf_load/perf_req_gen_get_txn.py
scripts/performance/perf_load/perf_utils.py

Add get_txn req to load

---

indy_node/utils/node_control_utils.py

Extend command result logging

---

scripts/performance/README.md
setup.py

Update load doc; Next plenum v586

---

pool_automation/roles/aws_manage/library/stateful_set.py
pool_automation/roles/aws_manage/library/test_stateful_set.py

Fixes AWS cleanup routine: waiting for ec2 in stances termination complete before trying security groups removal.

[Pool Automation][INDY-1784] Improves EC2 launching and termination routine

---

setup.py

[INDY-1687] bump plenum version

---

setup.py

Plenum bump 588

---

pool_automation/README.md
pool_automation/pool_create.yml
pool_automation/pool_destroy.yml
pool_automation/roles/aws_manage/defaults/main.yml
pool_automation/roles/aws_manage/library/stateful_set.py
pool_automation/roles/aws_manage/library/test_stateful_set.py
pool_automation/roles/aws_manage/molecule/cleanup/tests/test_default.py
pool_automation/roles/aws_manage/molecule/default/tests/test_default.py
pool_automation/roles/aws_manage/tasks/main.yml
pool_automation/roles/aws_manage/tasks/pre_checks.yml
pool_automation/roles/aws_manage/tasks/pre_up.yml
pool_automation/scripts/inventory-init.py

Changes:
- adds general tag `Project`  with default value `PoolAutomation` to cover all resources where it is possible
- sets first letters capital for all used predefined tags
- set lowercase for all resource names
- adds support for additional custom tags

[Pool Automation][INDY-1813][INDY-1828] Make AWS tags and names more accurate

---

setup.py

[INDY-1849] bump plenum

---

scripts/performance/setup.py

Fixes install requirements for performance sripts

---

setup.py

Plenum v597

---

setup.py

[INDY-1849] bump plenum version

---

scripts/get_metrics

Fix crash in get_metrics script

---

setup.py

Bump plenum 604

---

setup.py

INDY-1846: increment plenum version

---

scripts/performance/perf_load/__version__.py
scripts/performance/perf_load/perf_processes.py

Add genesis file test before client start

---

indy_node/server/domain_req_handler.py
indy_node/test/anon_creds/conftest.py
indy_node/test/claim_def/test_send_claim_def.py
indy_node/test/schema/test_send_get_schema.py
indy_node/test/state_proof/test_state_proof_for_get_requests.py
indy_node/test/write_permission/test_send_write_permission_anyone.py
indy_node/test/write_permission/test_send_write_permission_no_client.py

INDY-1862: Ref validation added

---

scripts/performance/README.md
scripts/performance/perf_load/__version__.py
scripts/performance/perf_load/perf_processes.py

Add test_conn param to script

---

indy_node/server/validator_info_tool.py
indy_node/test/validator_info/test_validator_info.py

Add update time and cur pkt versions to base json info

---

setup.py

Bump plenum 617

---

docs/auth_rules.md

[Auth rules] Add doc for describing current implemented auth rules

---

indy_node/test/node_txn/test_send_node_validation.py
setup.py

Bump plenum 619

---

setup.py

Bump Plenum 621

---

CHANGELOG.md

add Release Notes for 1.6.79

---

setup.py

Bump plenum 624

---

setup.py

INDY-1836: bump plenum.

---

setup.py

Bump plenum 632

---

scripts/performance/perf_load/__version__.py
scripts/performance/perf_load/perf_spike_load.py

Signed-off-by: olga.zheregelya <olga.zheregelya@dsr-company.com>

change hardcoded path to config for spike load test to parameter

---

CHANGELOG.md

Signed-off-by: olga.zheregelya <olga.zheregelya@dsr-company.com>

add release notes for version 1.6.80

---

setup.py

INDY-1926: bump plenum.

---

setup.py

INDY-1836/INDY-1926: bump plenum.

---

indy_common/authorize/auth_map.py
indy_common/authorize/authorizer.py
indy_common/test/auth/test_role_authorizer.py
indy_node/server/action_req_handler.py
indy_node/server/config_req_handler.py
indy_node/server/domain_req_handler.py
indy_node/test/nym_txn/test_nym_additional.py
indy_node/test/suspension/test_suspension.py
indy_node/test/txn_validation/test_send_get_nym_validation.py

INDY-1730: remove role checking in specific handlers.

---

setup.py

[pytest] pin pytest-asyncio version to 0.8.0 and python3-indy to 1.6.8

---

docs/requests.md
indy_common/config.py
indy_common/types.py
indy_node/test/schema/test_send_schema.py

INDY-1914: Fix and tests for schema attr limit

---

indy_node/test/catchup/test_batch_rejected_and_later_ordered_on_catchup.py
setup.py

 INDY-1876: bump plenum.

---

build-scripts/ubuntu-1604/prepare-package.sh

INDY-1919: Fix for correct packaging

---

indy_common/authorize/auth_map.py
indy_common/test/auth/test_auth_nym_with_new_auth_map.py
indy_node/test/conftest.py
indy_node/test/nym_txn/conftest.py
indy_node/test/nym_txn/test_demote_network_monitor.py
indy_node/test/nym_txn/test_nym_blacklisting.py

[INDY-1939] Add tests for demotes checking

---

indy_node/server/upgrader.py
indy_node/test/upgrade/test_pool_upgrade_same_time_different_days.py

INDY-1953: Fix for upgrade and test

---

setup.py

Plenum bump 658

---

scripts/validator-info

INDY-1920: fix a type problem with TransactionsStats in validator-info

---

indy_node/test/tools/test_nsreplay.py
setup.py

[INDY-1928] bump plenum version

---

setup.py

bump plenum 1.6.665

---

acceptance/indy-cli-batches/AS-03-01-identity-owner-anyone-can-write.batch
acceptance/indy-cli-batches/AS-03-01-identity-owner.batch
acceptance/indy-cli-batches/AS-03-01-steward.batch
acceptance/indy-cli-batches/AS-03-01-trust-anchor.batch
acceptance/indy-cli-batches/AS-03-01-trustee.batch

Signed-off-by: olga.zheregelya <olga.zheregelya@dsr-company.com>

add NETWORK_MONITOR to acceptance batches

---

setup.py

Bump plenum 1.6.667

---

setup.py

Bump plenum 1.6.669

---

indy_node/test/suspension/test_node_suspension.py
setup.py

Bump plenum 670

---

acceptance/indy-cli-batches/AS-03-01-steward.batch
acceptance/indy-cli-batches/expected/AS-03-01-identity-owner.expected
acceptance/indy-cli-batches/expected/AS-03-01-steward.expected
acceptance/indy-cli-batches/expected/AS-03-01-trust-anchor.expected
acceptance/indy-cli-batches/expected/AS-03-01-trustee.expected

Signed-off-by: olga.zheregelya <olga.zheregelya@dsr-company.com>

update expected results after INDY-1971 and INDY-1963 fixes, fix mistakes in steward scenario

---

setup.py

Bump plenum 674

---

setup.py

Bump plenum 677

---

setup.py

Bump plenum 679

---

setup.py

[INDY-1874] bump plenum

---

setup.py

Bump plenum 1.6.690

---

indy_common/authorize/auth_actions.py
indy_common/authorize/auth_cons_strategies.py
indy_common/authorize/auth_constraints.py
indy_common/authorize/auth_request_validator.py
indy_common/authorize/authorizer.py
indy_common/config.py
indy_common/test/auth/conftest.py
indy_common/test/auth/test_auth_constraint.py
indy_common/test/auth/test_auth_strategies.py
indy_common/test/auth/test_composite_authorizer.py
indy_common/test/auth/test_config_ledger_auth_strategy.py
indy_node/server/action_req_handler.py
indy_node/server/config_req_handler.py
indy_node/server/domain_req_handler.py
indy_node/server/node.py
indy_node/server/pool_req_handler.py
indy_node/test/state_proof/test_state_multi_proofs_for_get_requests.py
indy_node/test/write_permission/test_revocation_write_permission.py

[INDY-2001] Implement auth rule maps in config ledger

---

Jenkinsfile.cd

Bumps versionv of jenkins library to v1.2.1

---

indy_common/authorize/auth_cons_strategies.py
indy_common/authorize/auth_request_validator.py
indy_node/server/node.py
indy_node/test/schema/test_send_get_schema.py
setup.py

* add config_state filling on indy-node start
* add metric for counting rules from state using

[INDY-1995] prepare for testing auth rules

---

docs/source/auth_rules.md
docs/source/requests.md
docs/source/transactions.md

INDY-2003: add documentation for AUTH_RULE txn

---

setup.py

bump plenum to 1.6.716

---

indy_node/server/node.py

[INDY-1995] remove config state's filling

---

indy_common/authorize/auth_constraints.py
indy_common/authorize/auth_map.py
indy_common/test/auth/test_auth_strategies.py
indy_common/test/auth/test_composite_authorizer.py
indy_common/test/auth/test_role_authorizer.py
indy_node/server/config_req_handler.py
indy_node/test/auth_rule_change/test_auth_rule_transaction.py

[INDY-2003] add static validation for role value in constraints

---

scripts/current_validators

Signed-off-by: Mike Bailey <mike.bailey@evernym.com>

Add blskey_pop to list of properties to extract from ledger

---

Jenkinsfile.cd

[INDY-2016] update Jenkinsfile according to system tests changes

---

docs/source/auth_rules.md
indy_common/authorize/auth_map.py
indy_common/test/auth/test_auth_node_with_new_auth_map.py

[INDY-2003] make services as list

---

environment/vagrant/sandbox/DevelopmentEnvironment/AWS/scriptlets/indy-sdk/linux/pre/setup
environment/vagrant/sandbox/DevelopmentEnvironment/Virtualbox/Vagrantfile

fix 2 urls because indy-sdk's documents are arranged.

Fixed some urls to the correct path

---

README.md
docs/source/1.3_to_1.4_migration_guide.md
docs/source/requests-new.md
docs/source/requests.md
docs/source/start-nodes.md

Fixed missing urls by moving from docs to docs/source.

Changed some urls from docs to docs/source.

---

setup.py

Bump plenum 736

---

Jenkinsfile.cd

Sets specific version of indy-sdk for client environment in system tests

---

indy_node/test/catchup/test_batch_rejected_and_later_ordered_on_catchup.py

INDY-1946: Test fix

---

setup.py

ST-541 Bump plenum version

---

indy_common/authorize/auth_constraints.py
indy_common/authorize/authorizer.py

[ST-529] add set_metadata method

---

indy_node/test/helper.py

[ST-520] modify helper in tests

---

indy_common/authorize/auth_actions.py
indy_common/authorize/authorizer.py
indy_common/test/auth/test_auth_actions.py
indy_common/test/auth/test_auth_strategies.py
indy_common/test/types/test_attrib.py
indy_common/test/types/test_auth_rule_schema.py
indy_common/test/types/test_get_auth_rule_schema.py
indy_common/types.py
setup.py

INDY-2043: add AuthRuleValueField and change an auth key format

---

indy_common/types.py
indy_node/test/attrib_txn/test_attrib_txn_digest.py
setup.py

INDY-2051: Fix payload digest calculation

---

Jenkinsfile.cd

- bumps version of system tests
- optimizes system tests routine

System tests optimization

---

docs/source/auth_rules.md

update auth_map docs

---

indy_common/authorize/auth_actions.py

Fix AuthActionAdd

---

indy_node/test/auth_rule/test_auth_map.py

Add static tests to check changes in auth_map keys.

Add static tests for auth_map

---

indy_node/server/upgrade_log.py
indy_node/test/upgrade/test_upgrade_log.py

[Hotfix-1.7.1.rc1] makes pkg_name optional for upgrade log

---

CHANGELOG.md

Release notes 1.7.0

---

indy_common/authorize/authorizer.py
indy_common/test/auth/test_auth_anyone.py

ST-536: add a check for constraints with sig_count=0 in the Authorizer

---

indy_node/server/config_req_handler.py
indy_node/server/node.py
indy_node/test/request_handlers/test_update_state_config_req_handler.py
indy_node/test/txn_author_agreement/test_node_taa.py
setup.py

INDY-2067: Bump plenum version

---

indy_common/authorize/auth_constraints.py
indy_common/authorize/authorizer.py

[ST-531] More cleanly error message for OR constraints

---

ci/ubuntu.dockerfile
design/txn_author_agreement.md
indy_common/authorize/auth_map.py
indy_common/test/auth/test_txn_author_agreement_aml_with_new_auth_map.py
indy_node/server/config_req_handler.py
indy_node/test/auth_rule/auth_framework/test_auth_rule_using.py
indy_node/test/auth_rule/auth_framework/txn_author_agreement.py
indy_node/test/auth_rule/auth_framework/txn_author_agreement_aml.py
indy_node/test/auth_rule/test_auth_map.py
indy_node/test/txn_author_agreement/test_node_taa.py
setup.py

INDY-2068: TAA AML auth rules

---

indy_node/server/config_req_handler.py
indy_node/test/auth_rule/test_get_auth_rule.py

Remove the AUTH_RULE State marker from a GET_AUTH_RULE response

---

indy_node/test/auth_rule/auth_framework/basic.py
indy_node/test/auth_rule/auth_framework/test_auth_rule_using.py
indy_node/test/auth_rule/auth_framework/txn_author_agreement.py
setup.py

Bump plenum version to 1.8.0.dev794

---

scripts/performance/perf_load/perf_client_fees.py

INDY-2099: Add mint_addrs_count parameter to load script

---

Jenkinsfile.cd
setup.py

- bumps plenum
- disables rust trace logs in system tests

[INDY-2073] Bumps plenum to 1.8.0.dev802

---

scripts/performance/perf_load/__version__.py
scripts/performance/perf_load/perf_processes.py

INDY-2090: Fix log file output in perf load script

---

scripts/performance/perf_load/perf_gen_req_parser.py
scripts/performance/perf_load/perf_req_gen_get_auth_rules.py
scripts/performance/perf_load/perf_req_gen_get_taa.py
scripts/performance/perf_load/perf_req_gen_get_taa_aml.py
scripts/performance/perf_load/test/test_parser.py

INDY-2091: Load script extended with get txns

---

indy_node/test/auth_rule/auth_framework/add_attrib.py
indy_node/test/auth_rule/auth_framework/edit_attrib.py
indy_node/test/auth_rule/auth_framework/test_auth_rule_using.py

INDY-1975: Integration auth_map tests for attrib txn

---

scripts/performance/perf_load/perf_client.py
scripts/performance/perf_load/perf_req_gen_revoc.py

INDY-2090: Perf load script hotfixes

---

indy_node/server/config_req_handler.py
indy_node/test/auth_rule/test_get_auth_rule.py
scripts/performance/perf_load/perf_client.py

- fixes auth rule static validation for case when the rule is unique to `anyone_can_write` map
- updates tests that send AUTH_RULE as-is from what GET_AUTH_RULE returns
- removes obsolete workaround for load script

[INDY-2096] Minor updates

---

Jenkinsfile.cd

- INDY-2109: bumps jenkins to verision 2.1.1 where PyPI publishing is fixed
- INDY-2111: temporarily makes ignored failures during system tests running

[INDY-2109][INDY-2111] Fixes for CD pipeline

---

indy_node/server/config_req_handler.py
indy_node/test/txn_author_agreement/test_get_taa_aml.py

Fix config_req_handler

---

scripts/performance/perf_load/perf_client_fees.py
scripts/performance/perf_load/perf_req_gen_payment.py

INDY-2090: Additional fixes for perf load script

---

scripts/performance/perf_load/perf_client_fees.py

ST-568: fix setting fees aliases in laod script

---

scripts/performance/perf_load/perf_client.py
scripts/performance/perf_load/perf_client_fees.py
scripts/performance/perf_load/perf_req_gen.py
scripts/performance/perf_load/perf_req_gen_payment.py
scripts/performance/perf_load/perf_utils.py

ST-568: Improve stability and logging of token-related parts of load script

---

CHANGELOG.md

Release notes 1.8.0

---

scripts/performance/perf_load/perf_client.py
scripts/performance/perf_load/perf_client_fees.py

ST-568: add "set_auth_rules" boolean param to load test

---

docs/source/auth_rules.md
indy_common/authorize/authorizer.py
indy_node/server/domain_req_handler.py
indy_node/server/request_handlers/domain_req_handlers/schema_handler.py
indy_node/test/auth_rule/test_get_auth_rule.py
indy_node/test/request_handlers/test_schema_handler.py
indy_node/test/schema/test_send_schema.py

INDY-2077: fix bug in a reject with a Forbidden constraint message.

---

ci/ubuntu.dockerfile
setup.py

INDY-2083: Bump libindy and plenum version

---

indy_common/test/types/test_revoc_def_submit_schema.py
indy_common/types.py
indy_node/test/anon_creds/test_incorrect_revoc_reg_def.py

INDY-2142: add a validation for ISSUANCE_TYPE in revoc_reg_def

---

indy_node/server/request_handlers/domain_req_handlers/revoc_reg_entry_handler.py
indy_node/test/request_handlers/test_revoc_reg_entry_handler.py

[REG_ENTRY_VALIDATION] Add auth_rule validation for revoc_reg_entry

---

setup.py

[BUMP_PLENUM] bump plenum

---

indy_node/server/request_handlers/domain_req_handlers/attribute_handler.py
indy_node/server/request_handlers/domain_req_handlers/claim_def_handler.py
indy_node/server/request_handlers/domain_req_handlers/idr_cache_nym_handler.py
indy_node/server/request_handlers/domain_req_handlers/revoc_reg_def_handler.py
indy_node/server/request_handlers/domain_req_handlers/revoc_reg_entry_handler.py
indy_node/server/request_handlers/domain_req_handlers/schema_handler.py
setup.py

ST-523: Fixes for plugin integration

---

setup.py

INDY-2153 Bump plenum version

---

indy_node/server/request_handlers/config_req_handlers/node_upgrade_handler.py
indy_node/test/did/test_did_with_abbreviated_verkey.py
indy_node/test/state_proof/test_state_proof_for_get_requests.py
indy_node/test/upgrade/test_send_node_upgrade.py

Fix for NODE_UPGRADE txn

---

indy_node/test/state_proof/test_state_proof_for_get_requests.py
indy_node/test/upgrade/test_send_node_upgrade.py

Review fixes

---

indy_node/server/request_handlers/domain_req_handlers/claim_def_handler.py
indy_node/test/claim_def/test_claim_def_auth_rule.py

Fix for claim def edition

---

CHANGELOG.md

release notes 1.9.0

---

docs/source/auth_rules.md

Make documentation match CLI

---

Jenkinsfile.cd

[BUMP] bump jenkins shared lib to 2.2.1

---

Jenkinsfile.cd
Jenkinsfile.nightly
ci/pipeline.groovy

- adds new pipeline that performs system tests only and might be used in Jenkins jobs triggered periodically
- system testing logic has been moved to local shared groovy module which is consumed by both CD pipeline and nightly build

[INDY-2151] Nightly builds

---

docs/source/node-state-diagnostic-tools.md

Signed-off-by: Kenneth Ebert <ken@kindredlearning.com>
Replaces #1343 (same content changes, but fixed my repository issues and DCO)

Fix three typos

---

setup.py

INDY-2157: bump plenum

---

Jenkinsfile.cd
Jenkinsfile.nightly

[BUMP] bump indy-test-automation to 0.8.4

---

Jenkinsfile.ci

[TIMEOUT] increase timeout of pipeline to 90 minutes

---

setup.py

INDY-2164: bump plenum version

---

setup.py

INDY-2112: bump plenum version

---

.gitignore
ci/ubuntu.dockerfile
indy_node/test/state_proof/test_state_proof_for_get_requests.py
setup.py

INDY-2158: Unskip state proof case

---

setup.py

Bump plenum 847

---

indy_node/test/state_proof/test_state_proof_for_get_requests.py

INDY-2158: Skip test

---

ci/ubuntu.dockerfile
indy_node/test/auth_rule/auth_framework/test_auth_rule_using.py
setup.py

INDY-2157: bump libindy version

---

indy_node/server/request_handlers/action_req_handlers/validator_info_handler.py

[INDY-2182] Do not collect memory profiles info

---

design/transaction_endorder.md

INDY-1999: Transaction Endorser design

---

docs/source/requests-new.md
docs/source/requests.md
docs/source/transactions.md

- added `off_ledger_signature` field for AUTH_RULE(s)
- added Endorser descriptions
- described creation of new DIDs in permissionless case

INDY-2173: update docs

---

CHANGELOG.md

release notes 1.9.1

---

Jenkinsfile.cd
Jenkinsfile.nightly

Bump system tests

---

Jenkinsfile.nightly

Fix nightly tests

---

indy_common/authorize/authorizer.py
indy_common/test/auth/metadata/helper.py
indy_common/test/auth/metadata/test_auth_rule_with_metadata_composite.py
indy_common/test/auth/metadata/test_auth_rule_with_metadata_simple.py
indy_common/test/auth/test_endorser_authorizer.py

INDY-2199: do not require endorser if multi-signed by oner/monitor roles only.

---

build-scripts/ubuntu-1604/prepare-package.sh
setup.py

INDY-2176: get rid of a dateutil dependency since it's already defined in Plenum

---

setup.py

INDY-1335: bump plenum

---

indy_node/test/request_handlers/test_revert_uncommitted_state.py
setup.py

INDY-2208: bump plenum, fix test_revert_uncommitted_state

---

setup.py

INDY-2212: bump plenum

---

ci/ubuntu.dockerfile
setup.py

INDY-1954 -- Bump plenum ver

---

setup.py

INDY-2215: bump plenum version

---

README.md

Signed-off-by: dappsec <alank9+dappsec@gmail.com>

Fixing inconsistent capitalization in README

---

CODEOWNERS

Modify Codeowners list

---

Jenkinsfile.nightly

split new tests to separate pipeline branches

---

indy_node/test/nym_txn/test_create_did_without_endorser.py
indy_node/test/suspension/test_nym_suspension.py
setup.py

Signed-off-by: Nemanja Patrnogic <patrnogicnemanja@gmail.com>

INDY-2103: bump plenum version

---

indy_common/test/conftest.py
indy_node/test/anon_creds/conftest.py
indy_node/test/anon_creds/helper.py
indy_node/test/anon_creds/test_get_revoc_reg_delta_send_by_default.py
indy_node/test/anon_creds/test_get_revoc_reg_delta_send_by_demand.py
indy_node/test/anon_creds/test_get_revoc_reg_delta_unit.py
indy_node/test/anon_creds/test_get_revoc_reg_delta_validation.py
indy_node/test/anon_creds/test_get_revoc_reg_delta_with_none_results.py
indy_node/test/anon_creds/test_get_revoc_reg_entry.py
indy_node/test/anon_creds/test_get_revoc_reg_send.py
indy_node/test/anon_creds/test_state_proof_for_get_request.py
setup.py

INDY-2183: bump plenum

---

indy_node/test/anon_creds/conftest.py
setup.py

SN-7: bump plenum version

---

indy_node/test/auth_rule/test_revert_auth_rule_changing.py
setup.py

[INDY-1336] bump plenum version

---

setup.py

INDY-1340: bump plenum

---

setup.py

ST-623 Bump Indy-plenum version

---

setup.py

[INDY-2223] bump plenum's version

---

setup.py

INDY-2222: bump plenum version

---

setup.py

Signed-off-by: Nemanja Patrnogic <patrnogicnemanja@gmail.com>

INDY-2172: Bump plenum version

---

setup.py

ST-623 -- Add some more logs

---

setup.py

Signed-off-by: Nemanja Patrnogic <patrnogicnemanja@gmail.com>

[INDY-2213]: Bump plenum version

---

indy_node/test/pool_restart/test_pool_restart.py
indy_node/test/upgrade/test_force_upgrade_process_in_view_change.py
setup.py

INDY-2223: Bump plenum version

---

setup.py

INDY-2223: bump plenum

---

setup.py

INDY-2140: bump plenum

---

Jenkinsfile.cd
setup.py

bump plenum to stable version

---

setup.py

INDY-2222 -- Bump plenum

---

setup.py

INDY-2140: Bump plenum version

---

setup.py

INDY-2248: bump plenum

---

setup.py

INDY-2244: bump plenum

---

scripts/performance/perf_load/perf_req_gen_revoc.py

fix get revoc reg

---

ci/ubuntu.dockerfile
setup.py

INDY-2244: bump plenum and libindy

---

setup.py

Signed-off-by: Nemanja Patrnogic <patrnogicnemanja@gmail.com>

[INDY-2235]: Bump plenum version

---

Jenkinsfile.cd
Jenkinsfile.nightly

INDY-2274: bump system tests

---

indy_node/test/auth_rule/auth_framework/test_auth_rule_using.py
indy_node/test/conftest.py
setup.py

INDY-2268: bump plenum

---

CHANGELOG.md

add release notes

---

setup.py

INDY-2262: Bump plenum version

---

setup.py

[INDY-2236] bump plenum version

---

setup.py

INDY-2298: bump plenum

---

indy_node/test/catchup/test_txn_version_controller.py
indy_node/test/request_handlers/conftest.py
indy_node/test/request_handlers/test_auth_rule_1_9_1_handler.py
indy_node/test/request_handlers/test_auth_rule_handler.py
indy_node/test/request_handlers/test_auth_rules_handler.py

INDY-2292: add more tests for a state restoring

---

setup.py

INDY-2285: bump plenum

---

indy_node/server/txn_version_controller.py
indy_node/test/catchup/test_txn_version_controller.py
setup.py

INDY-2292: restore state with versioning

---

indy_common/config.py

[INDY-2303] Fix list of hold packages

---

setup.py

Signed-off-by: Nemanja Patrnogic <3052405+donqui@users.noreply.github.com>

[INDY-2289]: Bump plenum version

---

setup.py

INDY-2280: bump plenum

---

scripts/generate_bls_proof_of_possession
setup.py

INDY-2280: fix generation of key proof and bump plenum

---

indy_node/utils/node_control_utils.py

[INDY-2303] increase timeout for making apt cmd

---

docs/source/auth_rules.md

[INDY-2304] add Endorser using into auth_rules.md

---

indy_node/utils/node_control_tool.py

[INDY-2303] increase timeout for node_control_tool

---

setup.py

[INDY-2303] bump plenum version

---

indy_node/test/claim_def/conftest.py
indy_node/test/claim_def/test_claim_def_auth_rule.py
indy_node/test/claim_def/test_send_claim_def.py
indy_node/test/claim_def/test_send_get_claim_def.py

INDY-2306: tests to check that GET_CRED_DEF for large Schemas works

---

Jenkinsfile.ci

[CI] increase timeout for CI

---

indy_node/test/auth_rule/auth_framework/txn_author_agreement.py
indy_node/test/txn_author_agreement/test_node_taa.py
indy_node/test/txn_author_agreement/test_recover_taa_from_ledger.py
setup.py

INDY-2313: Update TAA-related namings

---

Jenkinsfile.cd
Jenkinsfile.nightly

bump sytem tests

---

indy_node/server/request_handlers/config_req_handlers/txn_author_agreement_handler_v1.py
indy_node/test/txn_author_agreement/test_recover_taa_from_ledger.py
setup.py

INDY-2316: bump plenum

---

docs/source/requests.md
docs/source/transactions.md

INDY-2302/2313: Update Transaction Author Agreement documentaion

---

indy_node/test/txn_author_agreement/test_recover_taa_from_ledger.py
setup.py

INDY-2316: update test_recover_taa_from_ledger

---

setup.py

INDY-2316: bump indy-plenum

---

scripts/performance/perf_load/perf_client.py

INDY-2316: Fix load script

---

docs/source/requests.md

This patch updates some more grammar in the requests.md documentation.

grammar in requests.md document

---

docs/source/requests.md

this propose change describes a request identifier and endorser clearer.

clearer request identifier description grammar.

---

indy_node/test/pool_restart/test_pool_restart.py
indy_node/test/request_handlers/test_revert_uncommitted_state.py
indy_node/test/view_change/test_view_change_during_alternating_unstash.py
setup.py

INDY-2324: Bump plenum version

---

setup.py

[INDY-2308] bump plenum version

---

indy_node/test/auth_rule/test_revert_auth_rule_changing.py
indy_node/test/suspension/test_node_suspension.py
setup.py

INDY-2322: bump plenum and fix tests

---

setup.py

INDY-2326: bump plenum

---

scripts/performance/README.md
scripts/performance/perf_load/perf_client.py
scripts/performance/perf_load/perf_gen_req_parser.py
scripts/performance/perf_load/perf_processes.py
scripts/performance/perf_load/perf_req_gen_demote.py
scripts/performance/perf_load/perf_req_gen_promote.py
scripts/performance/perf_load/perf_utils.py

add real demotion and promotion option

---

setup.py

[INDY-2326] bump plenum version

---

scripts/performance/README.md
scripts/performance/perf_load/perf_processes.py
scripts/performance/perf_load/perf_req_gen_demote.py
scripts/performance/perf_load/perf_req_gen_promote.py
scripts/performance/perf_load/perf_utils.py

improve demotion/promotion functionality

---

CHANGELOG.md
scripts/performance/perf_load/perf_processes.py

update release notes

---

docs/source/troubleshooting.md

INDY-2331: Node troubleshooting guide

---

Jenkinsfile.cd
Jenkinsfile.nightly

bump sustem tests

---

docs/source/troubleshooting.md

Update troubleshooting guide with node data structure

---

docs/source/requests.md
docs/source/transactions.md

Update requests and transactions docs for Rich Schema objects

---

CHANGELOG.md

release notes 1.12.3

---

CHANGELOG.md

release notes 1.12.4

---

README.md
ci/pipeline.groovy
ci/ubuntu.dockerfile
design/anoncreds.md
dev-setup/osx/setup-dev-dependencies.sh
dev-setup/ubuntu/setup-dev-depend-ubuntu14.sh
dev-setup/ubuntu/setup-dev-depend-ubuntu16.sh
docs/source/setup-dev.md
environment/docker/baseimage/indy-core-repo.preferences
indy_common/config.py
indy_node/test/upgrade/test_node_control_tool_resolves_dep_top_level.py
pool_automation/README.md
pool_automation/roles/indy_node/defaults/main.yml
pool_automation/roles/indy_node/molecule/resources/group_vars/all.yml
pool_automation/roles/indy_node/molecule/resources/tests/base/test_installed.py
pool_automation/roles/indy_node/tasks/main.yml
scripts/ansible/pool_install.yml
setup.py

This PR removes dependence on indy-crypto in code, comments, and documentation. It moves dependence to Ursa.

Remove indy-crypto

---

setup.py

Bump indy-plenum version

---

.github/workflows/README.md
.github/workflows/build.yaml
.github/workflows/build/Dockerfile
.github/workflows/build/README.md
.github/workflows/lint/Dockerfile
.github/workflows/lint/README.md
.gitignore
setup.py

This PR supersedes #1622 
Signed-off-by: Kevin Griffin <griffin.kev@gmail.com>

adds GitHub Actions and build containers

---

.github/workflows/build/Dockerfile
ci/ubuntu.dockerfile
setup.py

Bump libindy v.1.15.0-1618, bump plenum

---

Jenkinsfile.ci
setup.py

Bump libindy version for python wrapper

---

Jenkinsfile.cd

Pin pip version for CD

---

Jenkinsfile.cd
Jenkinsfile.ci
ci/pipeline.groovy

Pin pip for cd

---

ci/pipeline.groovy

Repair CD pipeline

---

Jenkinsfile.cd
Jenkinsfile.nightly

Bump test-automation version 0.8.43

---

.github/settings.yml

Signed-off-by: Ry Jones <ry@linux.com>

Add settings file

---

Jenkinsfile.nightly

Fix issue with nightly build.

---

.github/workflows/build.yaml
build-scripts/ubuntu-1604/build-indy-node.sh
build-scripts/ubuntu-1604/prepare-package.sh

This PR adds the building and publishing of the Python artifacts based on the workflow of Indy-Plenum.
It also adjusts the building of the debian distribution of node accordingly.

added building and publishing of python artifacts

---

dev-setup/ubuntu/init-dev-project.sh
dev-setup/ubuntu/setup-dev-python.sh
docs/source/setup-dev.md

Updated the dev-setup scripts for Ubuntu and edited documentation. 
Fixes #1609

Updated dev setup for ubuntu 16 and setup-dev.md

---

build-scripts/ubuntu-2004/build-indy-node.sh

updated libsodium from v18 to v23

---

.github/workflows/build/Dockerfile.ubuntu-2004

Remove duplicate Sovrin apt-key call

---

.github/workflows/indy_test_automation.yml

Signed-off-by: udosson <klemens@internet-sicherheit.de>

fixed typo in uploading detailed test failure results

---

README.md

Fixes the Gitpod Link

---

.github/workflows/build/Dockerfile
.github/workflows/lint/Dockerfile
Jenkinsfile.ci
ci/pipeline.groovy
indy_node/__init__.py
setup.py

removed pip imports

---

.github/workflows/PR.yaml
.github/workflows/Push.yaml
.github/workflows/WIPupdatePlenumDependency
.github/workflows/publishRelease.yaml
.github/workflows/releasepr.yaml
.github/workflows/tag.yaml

https://github.com/hyperledger/indy-shared-gha/issues/8 needs to be done first.

Pinned indy-shared-gha reference

---

.github/workflows/PR.yaml
.github/workflows/Push.yaml
.github/workflows/WIPupdatePlenumDependency
.github/workflows/publishRelease.yaml
.github/workflows/releasepr.yaml
.github/workflows/tag.yaml

consistent GHA variable substitution

---

.github/workflows/publishRelease.yaml

Fix missing component in publish release workflow.

---

.github/workflows/tag.yaml
setup.py

Update indy-plenum version.

---

indy_common/compat_set.py
indy_common/test/test_compat_set.py
indy_node/server/revocation_strategy.py

Fixes inconsistent transaction hashing for revocation registry deltas.

Add compat_set for supporting python3.5 set sorting behaviour

---

indy_common/test/test_util.py

Fix linting errors

---

build-scripts/ubuntu-2004/prepare-package.sh

Fixed prepare_package Script

---

.gitpod.Dockerfile
.gitpod.yml

Signed-off-by: pSchlarb <p.schlarb@esatus.com>

pinned gitpod base image

---

.github/actions/getNewNodeVersion/action.yaml
.github/workflows/WIPupdatePlenumDependency
.github/workflows/tag.yaml

- Following fix made here; https://github.com/sovrin-foundation/sovrin/pull/315

fixed correct checkout version & tags fetch

---

.github/workflows/PR.yaml
.github/workflows/Push.yaml
.github/workflows/build/Dockerfile.ubuntu-2004
.github/workflows/releasepr.yaml
.github/workflows/reuseable_test.yaml
build-scripts/ubuntu-2004/build-indy_node.sh
setup.py

Rocksdbfix

---

.github/workflows/Push.yaml
.github/workflows/releasepr.yaml

https://github.com/hyperledger/indy-test-automation/pull/129  needs to be merged before the integration will work

Test automation integration

---

.github/workflows/releasepr.yaml

https://github.com/hyperledger/indy-test-automation/pull/130 needs to be merged first and the tag from test automation then inserted.

test-automation integration

---

README.md
environment/docker/pool/README.md

docs: fixing broken links and to fix cgroup error

---

.github/workflows/tag.yaml

- Fix and update plenum installation

Update Bump Version Number workflow

---

.github/workflows/tag.yaml

- Fix additional plenum installation issues

Additional updates to Bump Version Number workflow

---

README.md

Update the documentation link in the README for Plenum

Update README.md with correct documentation link
